// SEO/GEO UI translations for all 8 languages (ar, en, es, ru, fr, de, tr, pt)
// Used by SSR pages: homepage block, company pages, guides, predictions

export const LANGS = ['ar', 'en', 'es', 'ru', 'fr', 'de', 'tr', 'pt'] as const;
export type Lang = (typeof LANGS)[number];

export const isLang = (l: unknown): l is Lang => typeof l === 'string' && (LANGS as readonly string[]).includes(l);

type Row = Record<Lang, string>;

const T: Record<string, Row> = {
  // ---------- Homepage SEO block ----------
  'home.what_you_get': {
    ar: 'ماذا تحصل عليه؟', en: 'What do you get?', es: '¿Qué obtienes?', ru: 'Что вы получаете?',
    fr: 'Que obtenez-vous ?', de: 'Was bekommen Sie?', tr: 'Ne kazanırsınız?', pt: 'O que você recebe?',
  },
  'home.b1': {
    ar: '<strong>تتبع المحافظ:</strong> راقب أرصدة شركات المراهنات المدعومة في مكان واحد',
    en: '<strong>Wallet Tracking:</strong> Monitor balances across supported betting companies in one place',
    es: '<strong>Seguimiento de carteras:</strong> Supervisa saldos de casas de apuestas compatibles en un solo lugar',
    ru: '<strong>Отслеживание кошельков:</strong> Следите за балансами поддерживаемых букмекеров в одном месте',
    fr: '<strong>Suivi des portefeuilles :</strong> Suivez les soldes des bookmakers pris en charge en un seul endroit',
    de: '<strong>Guthaben-Tracking:</strong> Behalten Sie die Salden der unterstützten Wettanbietern an einem Ort im Blick',
    tr: '<strong>Cüzdan Takibi:</strong> desteklenen bahis şirketlerinin bakiyesini tek yerden takip edin',
    pt: '<strong>Acompanhamento de carteiras:</strong> Monitore saldos de casas de apostas suportadas em um só lugar',
  },
  'home.b2': {
    ar: '<strong>تعويض الخسائر:</strong> احصل على نسب مئوية حقيقية على خسائرك وحوّلها إلى محفظتك',
    en: '<strong>Loss Compensation:</strong> Get real percentage refunds on your losses and move them to your wallet',
    es: '<strong>Compensación de pérdidas:</strong> Obtén reembolsos porcentuales reales y transfiérelos a tu cartera',
    ru: '<strong>Компенсация убытков:</strong> Получайте реальный процентный возврат потерь и переводите на свой кошелёк',
    fr: '<strong>Indemnisation des pertes :</strong> Obtenez un remboursement pourcentage réel et transférez-le vers votre portefeuille',
    de: '<strong>Verlustersatz:</strong> Erhalten Sie echte prozentuale Rückerstattungen und auf Ihr Wallet überweisen',
    tr: '<strong>Kayıp Tazminatı:</strong> Kayıplarınıza gerçek yüzdelik iade alın ve cüzdanınıza transfer edin',
    pt: '<strong>Compensação de perdas:</strong> Receba reembolsos percentuais reais e transfira para sua carteira',
  },
  'home.b3': {
    ar: '<strong>توقعات AI:</strong> تحليلات مباريات بمحرك Gemini مع احتمالات فوز ونتائج متوقعة',
    en: '<strong>AI Predictions:</strong> Match analysis by the Gemini engine with win probabilities and predicted scores',
    es: '<strong>Predicciones IA:</strong> Análisis de partidos con el motor Gemini, probabilidades y resultados previstos',
    ru: '<strong>AI-прогнозы:</strong> Анализ матчей от движка Gemini с вероятностями побед и прогнозами счета',
    fr: '<strong>Prédictions IA :</strong> Analyse des matchs par le moteur Gemini avec probabilités et scores prévus',
    de: '<strong>KI-Prognosen:</strong> Spielanalysen der Gemini-Engine mit Siegwahrscheinlichkeiten und TorgPrognosen',
    tr: '<strong>Yapay Zeka Tahminleri:</strong> Gemini motoruyla maç analizleri, kazanma olasılıkları ve skor tahminleri',
    pt: '<strong>Previsões de IA:</strong> Análises de jogos com o motor Gemini, probabilidades e placares previstos',
  },
  'home.b4': {
    ar: '<strong>يانصيب عادل:</strong> سحوبات مُثبتة بتشفير SHA-256 مع جوائز تصل إلى 10,000$',
    en: '<strong>Fair Lottery:</strong> SHA-256 provably fair draws with prizes up to $10,000',
    es: '<strong>Lotería justa:</strong> Sorteos demostrablemente justos con SHA-256 y premios de hasta 10.000 $',
    ru: '<strong>Честная лотерея:</strong> Прозрачные розыгрыши SHA-256 с призами до 10 000 $',
    fr: '<strong>Loterie équitable :</strong> Tirages vérifiables SHA-256 avec des prix jusqu’à 10 000 $',
    de: '<strong>Faires Lotto:</strong> SHA-256 nachweisbar faire Ziehungen mit Preisen bis 10.000 $',
    tr: '<strong>Adil Piyango:</strong> SHA-256 ile kanıtlanabilir adaletli çekilişler, 10.000$’a kadar ödüller',
    pt: '<strong>Loteria justa:</strong> Sorteios comprovadamente justos com SHA-256 e prêmios de até US$ 10.000',
  },
  'home.b5': {
    ar: '<strong>تطبيق جوال:</strong> APK + PWA + iOS مع إشعارات لحظية',
    en: '<strong>Mobile App:</strong> APK + PWA + iOS with real-time notifications',
    es: '<strong>App móvil:</strong> APK + PWA + iOS con notificaciones en tiempo real',
    ru: '<strong>Мобильное приложение:</strong> APK + PWA + iOS с уведомлениями в реальном времени',
    fr: '<strong>Application mobile :</strong> APK + PWA + iOS avec notifications en temps réel',
    de: '<strong>Mobile App:</strong> APK + PWA + iOS mit Echtzeit-Benachrichtigungen',
    tr: '<strong>Mobil Uygulama:</strong> Gerçek zamanlı bildirimli APK + PWA + iOS',
    pt: '<strong>Aplicativo móvel:</strong> APK + PWA + iOS com notificações em tempo real',
  },
  'home.keywords_label': {
    ar: 'تصفّح', en: 'Explore', es: 'Explora', ru: 'Изучите',
    fr: 'Explorez', de: 'Entdecken', tr: 'Keşfet', pt: 'Explore',
  },
  'link.guide_comp': {
    ar: 'دليل التعويض', en: 'Compensation Guide', es: 'Guía de compensación', ru: 'Руководство по компенсации',
    fr: 'Guide d’indemnisation', de: 'Erstattungsleitfaden', tr: 'Tazminat Rehberi', pt: 'Guia de compensação',
  },
  'link.guide_ai': {
    ar: 'دليل توقعات AI', en: 'AI Predictions Guide', es: 'Guía de predicciones IA', ru: 'Руководство по AI-прогнозам',
    fr: 'Guide des prédictions IA', de: 'KI-Prognoseleitfaden', tr: 'YZ Tahmin Rehberi', pt: 'Guia de previsões de IA',
  },
  'link.guide_lottery': {
    ar: 'اليانصيب العادل', en: 'Fair Lottery', es: 'Lotería justa', ru: 'Честная лотерея',
    fr: 'Loterie équitable', de: 'Faires Lotto', tr: 'Adil Piyango', pt: 'Loteria justa',
  },
  'link.guide_1xbet': {
    ar: 'دليل بونص 1xBet', en: '1xBet Bonus Guide', es: 'Guía de bonos 1xBet', ru: 'Гайд по бонусам 1xBet',
    fr: 'Guide des bonus 1xBet', de: '1xBet Bonus-Leitfaden', tr: '1xBet Bonus Rehberi', pt: 'Guia de bônus 1xBet',
  },
  'link.guide_wallet': {
    ar: 'تتبّع المحافظ', en: 'Wallet Tracking', es: 'Seguimiento de carteras', ru: 'Отслеживание кошельков',
    fr: 'Suivi des portefeuilles', de: 'Wallet-Tracking', tr: 'Cüzdan Takibi', pt: 'Acompanhamento de carteiras',
  },
  'link.guide_odds': {
    ar: 'دليل الأرقام', en: 'Odds Explained', es: 'Cuotas explicadas', ru: 'Как читать коэффициенты',
    fr: 'Cotes expliquées', de: 'Quoten erklärt', tr: 'Oranlar Açıklamalı', pt: 'Odds explicadas',
  },
  'link.guide_bankroll': {
    ar: 'إدارة الرصيد', en: 'Bankroll Management', es: 'Gestión de bankroll', ru: 'Управление банкроллом',
    fr: 'Gestion de bankroll', de: 'Bankroll-Management', tr: 'Bankroll Yönetimi', pt: 'Gestão de bankroll',
  },
  'link.guide_live': {
    ar: 'المراهنات المباشرة', en: 'Live Betting', es: 'Apuestas en vivo', ru: 'Live-ставки',
    fr: 'Paris en direct', de: 'Live-Wetten', tr: 'Canlı Bahis', pt: 'Apostas ao vivo',
  },
  'link.guide_responsible': {
    ar: 'اللعب المسؤول', en: 'Responsible Gambling', es: 'Juego responsable', ru: 'Ответственная игра',
    fr: 'Jeu responsable', de: 'Verantwortungsvolles Spielen', tr: 'Sorumlu Bahis', pt: 'Jogo responsável',
  },

  // ---------- Company pages ----------
  'company.subtitle': {
    ar: 'دليل التعويضات والبونص الكامل', en: 'Complete Compensation & Bonus Guide',
    es: 'Guía completa de compensación y bonos', ru: 'Полное руководство по компенсации и бонусам',
    fr: 'Guide complet des indemnisations et bonus', de: 'Vollständiger Erstattungs- und Bonusleitfaden',
    tr: 'Kapsamlı Tazminat ve Bonus Rehberi', pt: 'Guia completo de compensação e bônus',
  },
  'company.meta_desc': {
    ar: 'كل ما تحتاج معرفته عن {name} عبر {brand}: أكواد الخصم، طلبات التعويض، تحميل التطبيق، واستراتيجيات مدروسة.',
    en: 'Everything you need to know about {name} on {brand}: promo codes, compensation claims, app download, and practical strategy guides.',
    es: 'Todo lo que necesitas saber sobre {name} en {brand}: códigos promocionales, solicitudes de compensación, descarga de la app y estrategias prácticas.',
    ru: 'Всё, что нужно знать о {name} на {brand}: промокоды, запросы на компенсацию, скачивание приложения и практические стратегии.',
    fr: 'Tout ce qu’il faut savoir sur {name} sur {brand} : codes promo, demandes d’indemnisation, téléchargement de l’app et stratégies pratiques.',
    de: 'Alles über {name} auf {brand}: Aktionscodes, Erstattungsanträge, App-Download und praktische Strategien.',
    tr: '{brand} üzerinde {name} hakkında bilmeniz gereken her şey: promosyon kodları, tazminat talepleri, uygulama indirme ve pratik stratejiler.',
    pt: 'Tudo sobre {name} na {brand}: códigos promocionais, solicitações de compensação, download do app e estratégias práticas.',
  },
  'company.og_desc': {
    ar: 'دليل {name} الكامل على {brand}: تعويضات، بونص، تحميل',
    en: 'The complete {name} guide on {brand}: compensation, bonuses, download',
    es: 'La guía completa de {name} en {brand}: compensación, bonos, descarga',
    ru: 'Полное руководство по {name} на {brand}: компенсация, бонусы, скачивание',
    fr: 'Le guide complet de {name} sur {brand} : indemnisation, bonus, téléchargement',
    de: 'Der vollständige {name}-Leitfaden auf {brand}: Erstattung, Boni, Download',
    tr: '{brand} üzerinde kapsamlı {name} rehberi: tazminat, bonus, indirme',
    pt: 'O guia completo de {name} na {brand}: compensação, bônus, download',
  },
  'company.badge_verified': { ar: 'تعويضات موثقة', en: 'Verified Compensation', es: 'Compensación verificada', ru: 'Проверенная компенсация', fr: 'Indemnisation vérifiée', de: 'Verifizierte Erstattung', tr: 'Doğrulanmış Tazminat', pt: 'Compensação verificada' },
  'company.badge_promo': { ar: 'برومو:', en: 'Promo:', es: 'Promo:', ru: 'Промо:', fr: 'Promo :', de: 'Promo:', tr: 'Promo:', pt: 'Promo:' },
  'company.badge_apk': { ar: 'APK متاح', en: 'APK Available', es: 'APK disponible', ru: 'APK доступен', fr: 'APK disponible', de: 'APK verfügbar', tr: 'APK Mevcut', pt: 'APK disponível' },
  'company.badge_instant': { ar: 'تحويل سريع', en: 'Quick Transfer', es: 'Transferencia rápida', ru: 'Быстрый перевод', fr: 'Transfert rapide', de: 'Schnelle Überweisung', tr: 'Hızlı Transfer', pt: 'Transferência rápida' },
  'company.promo_title': { ar: 'كود الخصم الشريك', en: 'Partner Promo Code', es: 'Código promocional del socio', ru: 'Промокод партнёра', fr: 'Code promo partenaire', de: 'Partner-Aktionscode', tr: 'Ortak Promosyon Kodu', pt: 'Código promocional do parceiro' },
  'company.promo_note': {
    ar: 'استخدم هذا الكود عند التسجيل للحصول على بونص الترحيب',
    en: 'Use this code during registration to get the welcome bonus',
    es: 'Usa este código al registrarte para obtener el bono de bienvenida',
    ru: 'Используйте этот код при регистрации, чтобы получить приветственный бонус',
    fr: 'Utilisez ce code lors de l’inscription pour obtenir le bonus de bienvenue',
    de: 'Verwenden Sie diesen Code bei der Registrierung für den Willkommensbonus',
    tr: 'Kayıt olurken bu kodu kullanın ve hoş geldin bonusunu alın',
    pt: 'Use este código no cadastro para receber o bônus de boas-vindas',
  },
  'company.steps_title': {
    ar: 'كيف تحصل على تعويض {name}؟', en: 'How to claim {name} compensation?', es: '¿Cómo reclamar la compensación de {name}?',
    ru: 'Как получить компенсацию от {name}?', fr: 'Comment obtenir l’indemnisation de {name} ?', de: 'Wie erhalte ich die {name}-Erstattung?',
    tr: '{name} tazminatını nasıl alırsınız?', pt: 'Como solicitar a compensação da {name}?',
  },
  'company.step1': { ar: 'سجّل حسابك عبر {brand} بالكود <code>{promo}</code>', en: 'Register your account on {brand} with code <code>{promo}</code>', es: 'Registra tu cuenta en {brand} con el código <code>{promo}</code>', ru: 'Зарегистрируйте аккаунт на {brand} с кодом <code>{promo}</code>', fr: 'Inscrivez votre compte sur {brand} avec le code <code>{promo}</code>', de: 'Registrieren Sie Ihr Konto bei {brand} mit dem Code <code>{promo}</code>', tr: '{brand}’de <code>{promo}</code> koduyla hesabınızı açın', pt: 'Cadastre sua conta na {brand} com o código <code>{promo}</code>' },
  'company.step2': { ar: 'وثّق رصيدك بلقطة شاشة من محفظتك في {name}', en: 'Verify your balance with a screenshot of your {name} wallet', es: 'Verifica tu saldo con una captura de tu cartera de {name}', ru: 'Подтвердите баланс скриншотом кошелька {name}', fr: 'Vérifiez votre solde avec une capture de votre portefeuille {name}', de: 'Bestätigen Sie Ihr Guthaben mit einem Screenshot Ihres {name}-Wallets', tr: '{name} cüzdanınızın ekran görüntüsüyle bakiyenizi doğrulayın', pt: 'Confirme seu saldo com uma captura da sua carteira da {name}' },
  'company.step3': { ar: 'قدّم طلب التعويض من صفحة المحافظ في {brand}', en: 'Submit the compensation request from the wallets page in {brand}', es: 'Envía la solicitud de compensación desde la página de carteras en {brand}', ru: 'Отправьте запрос на компенсацию со страницы кошельков на {brand}', fr: 'Envoyez la demande d’indemnisation depuis la page des portefeuilles sur {brand}', de: 'Senden Sie den Erstattungsantrag über die Wallet-Seite auf {brand}', tr: '{brand}’deki cüzdanlar sayfasından tazminat talebi gönderin', pt: 'Envie a solicitação de compensação pela página de carteiras na {brand}' },
  'company.step4': { ar: 'استلم نسبتك وتُضاف مباشرة لرصيدك المجمد', en: 'Receive your percentage — it is added directly to your frozen balance', es: 'Recibe tu porcentaje: se añade directamente a tu saldo congelado', ru: 'Получите свой процент — он добавится напрямую к замороженному балансу', fr: 'Recevez votre pourcentage — il est ajouté directement à votre solde gelé', de: 'Erhalten Sie Ihren Prozentsatz — er wird direkt Ihrem eingefrorenen Guthaben gutgeschrieben', tr: 'Yüzde payınızı alın — doğrudan dondurulmuş bakiyenize eklenir', pt: 'Receba seu percentual — ele é adicionado diretamente ao seu saldo congelado' },
  'company.step5': { ar: 'حوّل أو اسحب التعويض لحسابك البنكي أو محفظتك', en: 'Transfer or withdraw the compensation to your bank account or wallet', es: 'Transfiere o retira la compensación a tu cuenta bancaria o cartera', ru: 'Переведите или выведите компенсацию на банковский счёт или кошелёк', fr: 'Transférez ou retirez l’indemnisation vers votre compte bancaire ou portefeuille', de: 'Überweisen oder heben Sie die Erstattung auf Ihr Bankkonto oder Wallet ab', tr: 'Tazminatı banka hesabınıza veya cüzdanınıza aktarın/çekin', pt: 'Transfira ou saque a compensação para sua conta bancária ou carteira' },
  'company.why_title': { ar: 'لماذا {name} عبر {brand}؟', en: 'Why {name} through {brand}?', es: '¿Por qué {name} con {brand}?', ru: 'Почему {name} через {brand}?', fr: 'Pourquoi {name} via {brand} ?', de: 'Warum {name} über {brand}?', tr: 'Neden {brand} üzerinden {name}?', pt: 'Por que a {name} pela {brand}?' },
  'company.why1': { ar: '<strong>تعويض حقيقي</strong> — نسب مئوية فعلية على خسائرك', en: '<strong>Real compensation</strong> — actual percentages on your losses', es: '<strong>Compensación real</strong> — porcentajes reales sobre tus pérdidas', ru: '<strong>Реальная компенсация</strong> — настоящие проценты с ваших потерь', fr: '<strong>Indemnisation réelle</strong> — pourcentages réels sur vos pertes', de: '<strong>Echte Erstattung</strong> — tatsächliche Prozente auf Ihre Verluste', tr: '<strong>Gerçek tazminat</strong> — kayıplarınızda gerçek yüzdelik oranlar', pt: '<strong>Compensação real</strong> — percentuais reais sobre suas perdas' },
  'company.why2': { ar: '<strong>أمان متقدّم</strong> — تشفير بنكي وحماية ضد الاختراق', en: '<strong>Strong security</strong> — banking-grade encryption and breach protection', es: '<strong>Seguridad sólida</strong> — cifrado bancario y protección contra intrusiones', ru: '<strong>Надёжная защита</strong> — банковское шифрование и защита от взломов', fr: '<strong>Sécurité renforcée</strong> — chiffrement bancaire et protection contre les intrusions', de: '<strong>Starke Sicherheit</strong> — Bankenverschlüsselung und Schutz vor Angriffen', tr: '<strong>Güçlü güvenlik</strong> — bankacılık düzeyinde şifreleme ve koruma', pt: '<strong>Segurança reforçada</strong> — criptografia bancária e proteção contra invasões' },
  'company.why3': { ar: '<strong>تحويل إلى محفظتك</strong> — حوّل التعويض إلى محفظتك أو حسابك', en: '<strong>Wallet transfer</strong> — move compensation to your wallet or bank account', es: '<strong>Transferencia a tu cartera</strong> — mueve la compensación a tu cartera o cuenta', ru: '<strong>Перевод на кошелёк</strong> — переведите компенсацию на кошелёк или счёт', fr: '<strong>Transfert vers portefeuille</strong> — envoyez l’indemnisation vers votre portefeuille ou compte', de: '<strong>Wallet-Überweisung</strong> — überweisen Sie die Erstattung auf Ihr Wallet oder Konto', tr: '<strong>Cüzdana transfer</strong> — tazminatı cüzdanınıza veya hesabınıza aktarın', pt: '<strong>Transferência para carteira</strong> — mova a compensação para sua carteira ou conta' },
  'company.why4': { ar: '<strong>دعم عربي</strong> — فريق يتحدث لغتك', en: '<strong>Native-language support</strong> — a team that speaks your language', es: '<strong>Soporte en tu idioma</strong> — un equipo que habla tu lengua', ru: '<strong>Поддержка на вашем языке</strong> — команда, говорящая на вашем языке', fr: '<strong>Support dans votre langue</strong> — une équipe qui parle votre langue', de: '<strong>Support in Ihrer Sprache</strong> — ein Team, das Ihre Sprache spricht', tr: '<strong>Yerel dilde destek</strong> — sizin dilinizi konuşan bir ekip', pt: '<strong>Suporte no seu idioma</strong> — uma equipe que fala a sua língua' },
  'company.why5': { ar: '<strong>تطبيق جوال</strong> — APK + PWA + iOS', en: '<strong>Mobile app</strong> — APK + PWA + iOS', es: '<strong>App móvil</strong> — APK + PWA + iOS', ru: '<strong>Мобильное приложение</strong> — APK + PWA + iOS', fr: '<strong>Application mobile</strong> — APK + PWA + iOS', de: '<strong>Mobile App</strong> — APK + PWA + iOS', tr: '<strong>Mobil uygulama</strong> — APK + PWA + iOS', pt: '<strong>Aplicativo móvel</strong> — APK + PWA + iOS' },
  'company.why6': { ar: '<strong>AI توقعات</strong> — تحليل مباريات بالذكاء الاصطناعي', en: '<strong>AI predictions</strong> — AI-powered match analysis', es: '<strong>Predicciones IA</strong> — análisis de partidos con IA', ru: '<strong>AI-прогнозы</strong> — анализ матчей на основе ИИ', fr: '<strong>Prédictions IA</strong> — analyse des matchs par IA', de: '<strong>KI-Prognosen</strong> — KI-gestützte Spielanalysen', tr: '<strong>YZ tahminleri</strong> — yapay zekâ destekli maç analizi', pt: '<strong>Previsões de IA</strong> — análises de jogos com IA' },
  'company.faq_title': { ar: 'الأسئلة الشائعة عن {name}', en: 'Frequently asked questions about {name}', es: 'Preguntas frecuentes sobre {name}', ru: 'Частые вопросы о {name}', fr: 'Questions fréquentes sur {name}', de: 'Häufige Fragen zu {name}', tr: '{name} hakkında sık sorulan sorular', pt: 'Perguntas frequentes sobre {name}' },
  'company.faq1q': { ar: 'كيف أحصل على تعويض {name}؟', en: 'How do I get {name} compensation?', es: '¿Cómo obtengo la compensación de {name}?', ru: 'Как получить компенсацию от {name}?', fr: 'Comment obtenir l’indemnisation de {name} ?', de: 'Wie erhalte ich die {name}-Erstattung?', tr: '{name} tazminatını nasıl alırım?', pt: 'Como obtenho a compensação da {name}?' },
  'company.faq1a': { ar: 'سجّل عبر {brand}، وثّق رصيدك، قدّم طلب التعويض، واستلم نسبتك مباشرة.', en: 'Register through {brand}, verify your balance, submit the claim, and receive your percentage directly.', es: 'Regístrate en {brand}, verifica tu saldo, envía la solicitud y recibe tu porcentaje directamente.', ru: 'Зарегистрируйтесь на {brand}, подтвердите баланс, отправьте запрос и получите процент напрямую.', fr: 'Inscrivez-vous sur {brand}, vérifiez votre solde, envoyez la demande et recevez votre pourcentage directement.', de: 'Registrieren Sie sich bei {brand}, bestätigen Sie Ihr Guthaben, senden Sie den Antrag und erhalten Sie Ihren Prozentsatz direkt.', tr: '{brand}’e kayıt olun, bakiyenizi doğrulayın, talebi gönderin ve yüzde payınızı doğrudan alın.', pt: 'Cadastre-se na {brand}, confirme seu saldo, envie a solicitação e receba seu percentual diretamente.' },
  'company.faq2q': { ar: 'ما هو كود الخصم؟', en: 'What is the promo code?', es: '¿Cuál es el código promocional?', ru: 'Какой промокод?', fr: 'Quel est le code promo ?', de: 'Wie lautet der Aktionscode?', tr: 'Promosyon kodu nedir?', pt: 'Qual é o código promocional?' },
  'company.faq2a': { ar: 'كود الخصم هو <code>{promo}</code> — استخدمه عند التسجيل.', en: 'The promo code is <code>{promo}</code> — use it when registering.', es: 'El código promocional es <code>{promo}</code> — úsalo al registrarte.', ru: 'Промокод: <code>{promo}</code> — используйте при регистрации.', fr: 'Le code promo est <code>{promo}</code> — utilisez-le à l’inscription.', de: 'Der Aktionscode lautet <code>{promo}</code> — verwenden Sie ihn bei der Registrierung.', tr: 'Promosyon kodu: <code>{promo}</code> — kayıt olurken kullanın.', pt: 'O código promocional é <code>{promo}</code> — use-o no cadastro.' },
  'company.faq3q': { ar: 'هل {name} آمن؟', en: 'Is {name} safe?', es: '¿Es seguro {name}?', ru: 'Безопасен ли {name}?', fr: '{name} est-il sûr ?', de: 'Ist {name} sicher?', tr: '{name} güvenli mi?', pt: 'A {name} é segura?' },
  'company.faq3a': { ar: 'نعم، {brand} يتحقق من أمان كل شركة قبل إضافتها للمنصة.', en: 'Yes, {brand} verifies the safety of every company before adding it to the platform.', es: 'Sí, {brand} verifica la seguridad de cada compañía antes de añadirla a la plataforma.', ru: 'Да, {brand} проверяет безопасность каждой компании перед добавлением на платформу.', fr: 'Oui, {brand} vérifie la sécurité de chaque société avant de l’ajouter à la plateforme.', de: 'Ja, {brand} prüft die Sicherheit jedes Anbieters, bevor er zur Plattform hinzugefügt wird.', tr: 'Evet, {brand} her şirketi platforma eklemeden önce güvenlik açısından doğrular.', pt: 'Sim, a {brand} verifica a segurança de cada empresa antes de adicioná-la à plataforma.' },
  'company.faq4q': { ar: 'كم يستغرق وصول التعويض؟', en: 'How long does compensation take?', es: '¿Cuánto tarda la compensación?', ru: 'Сколько занимает компенсация?', fr: 'Combien de temps prend l’indemnisation ?', de: 'Wie lange dauert die Erstattung?', tr: 'Tazminat ne kadar sürer?', pt: 'Quanto tempo leva a compensação?' },
  'company.faq4a': { ar: 'عادة خلال 24 ساعة كحد أقصى.', en: 'Usually within 24 hours at most.', es: 'Normalmente en un máximo de 24 horas.', ru: 'Обычно максимум в течение 24 часов.', fr: 'Généralement en 24 heures au maximum.', de: 'Normalerweise höchstens innerhalb von 24 Stunden.', tr: 'Genellikle en geç 24 saat içinde.', pt: 'Normalmente em até 24 horas.' },
  'company.related_title': { ar: 'صفحات ذات صلة', en: 'Related pages', es: 'Páginas relacionadas', ru: 'Похожие страницы', fr: 'Pages associées', de: 'Ähnliche Seiten', tr: 'İlgili sayfalar', pt: 'Páginas relacionadas' },

  // ---------- CTAs ----------
  'cta.companies': { ar: 'كل الشركات', en: 'All Companies', es: 'Todas las compañías', ru: 'Все компании', fr: 'Toutes les sociétés', de: 'Alle Unternehmen', tr: 'Tüm Şirketler', pt: 'Todas as empresas' },
  'cta.download': { ar: 'تحميل التطبيق', en: 'Download App', es: 'Descargar app', ru: 'Скачать приложение', fr: 'Télécharger l’app', de: 'App herunterladen', tr: 'Uygulamayı İndir', pt: 'Baixar o app' },
  'cta.ai': { ar: 'توقعات AI', en: 'AI Predictions', es: 'Predicciones IA', ru: 'AI-прогнозы', fr: 'Prédictions IA', de: 'KI-Prognosen', tr: 'YZ Tahminleri', pt: 'Previsões de IA' },

  // ---------- Guides chrome ----------
  'guides.brand_line': { ar: 'هذا الدليل من <strong>{brand}</strong> — {tagline}. {intro}', en: 'This guide is from <strong>{brand}</strong> — {tagline}. {intro}', es: 'Esta guía es de <strong>{brand}</strong> — {tagline}. {intro}', ru: 'Это руководство от <strong>{brand}</strong> — {tagline}. {intro}', fr: 'Ce guide vient de <strong>{brand}</strong> — {tagline}. {intro}', de: 'Dieser Leitfaden stammt von <strong>{brand}</strong> — {tagline}. {intro}', tr: 'Bu rehber <strong>{brand}</strong> tarafından — {tagline}. {intro}', pt: 'Este guia é da <strong>{brand}</strong> — {tagline}. {intro}' },
  'guides.steps_title': { ar: 'الخطوات', en: 'Steps', es: 'Pasos', ru: 'Шаги', fr: 'Étapes', de: 'Schritte', tr: 'Adımlar', pt: 'Etapas' },
  'guides.faq_title': { ar: 'الأسئلة الشائعة', en: 'Frequently Asked Questions', es: 'Preguntas frecuentes', ru: 'Частые вопросы', fr: 'Questions fréquentes', de: 'Häufige Fragen', tr: 'Sık Sorulan Sorular', pt: 'Perguntas frequentes' },
  'guides.cta_home': { ar: 'الصفحة الرئيسية', en: 'Home Page', es: 'Página de inicio', ru: 'Главная страница', fr: 'Page d’accueil', de: 'Startseite', tr: 'Ana Sayfa', pt: 'Página inicial' },
  'guides.related_title': { ar: 'أدلة ذات صلة', en: 'Related Guides', es: 'Guías relacionadas', ru: 'Похожие руководства', fr: 'Guides associés', de: 'Verwandte Leitfäden', tr: 'İlgili Rehberler', pt: 'Guias relacionados' },

  // ---------- Hub pages (/companies, /guides) ----------
  'hub.companies_h1': {
    ar: 'دليل شركات المراهنات الشريكة',
    en: 'Betting Companies Directory',
    es: 'Directorio de casas de apuestas',
    ru: 'Каталог букмекерских компаний',
    fr: 'Répertoire des bookmakers',
    de: 'Verzeichnis von Wettanbietern',
    tr: 'Bahis Şirketleri Dizini',
    pt: 'Diretório de casas de apostas',
  },
  'hub.companies_desc': {
    ar: 'قارن أكواد الخصم، نسب التعويض، وسرعة التحويل لكل شركة شريكة عبر {brand} مع روابط مخصصة لكل شركة.',
    en: 'Compare promo codes, compensation rates and payout speed for every partner company via {brand}, with a dedicated page for each.',
    es: 'Compara códigos de descuento, tasas de compensación y velocidad de pago de cada empresa asociada vía {brand}, con página dedicada.',
    ru: 'Сравните промокоды, проценты компенсации и скорость выплат каждой партнёрской компании через {brand}, у каждой есть отдельная страница.',
    fr: 'Comparez codes promo, taux d’indemnisation et rapidité de paiement de chaque société partenaire via {brand}, avec une page dédiée.',
    de: 'Vergleiche Promo-Codes, Erstattungsquoten und Auszahlungsgeschwindigkeit aller Partnerunternehmen über {brand} — jede hat eine eigene Seite.',
    tr: '{brand} üzerinden her ortak şirketin promosyon kodlarını, tazminat oranlarını ve ödeme hızını karşılaştırın — her biri için özel sayfa.',
    pt: 'Compare códigos promocionais, taxas de compensação e velocidade de pagamento de cada empresa parceira via {brand}, com página dedicada.',
  },
  'hub.guides_h1': {
    ar: 'كل الأدلة والشروحات',
    en: 'All Guides & Tutorials',
    es: 'Todas las guías y tutoriales',
    ru: 'Все руководства и инструкции',
    fr: 'Tous les guides et tutoriels',
    de: 'Alle Leitfäden und Tutorials',
    tr: 'Tüm Rehberler ve Eğiticiler',
    pt: 'Todos os guias e tutoriais',
  },
  'hub.guides_desc': {
    ar: 'أدلة خطوة بخطوة عن التعويضات، فك التجميد، توقعات الذكاء الاصطناعي، اليانصيب العادل، بونص 1xBet وتتبّع المحافظ.',
    en: 'Step-by-step guides on compensation, unfreezing, AI predictions, fair lottery, 1xBet bonuses and wallet tracking.',
    es: 'Guías paso a paso sobre compensación, desbloqueo, predicciones IA, lotería justa, bonos 1xBet y seguimiento de carteras.',
    ru: 'Пошаговые руководства по компенсации, разморозке, AI-прогнозам, честной лотерее, бонусам 1xBet и отслеживанию кошельков.',
    fr: 'Guides étape par étape : indemnisation, déblocage, prédictions IA, loteria équitable, bonus 1xBet et suivi des portefeuilles.',
    de: 'Schritt-für-Schritt-Leitfäden zu Erstattung, Entsperren, KI-Prognosen, faires Lotto, 1xBet-Boni und Wallet-Tracking.',
    tr: 'Tazminat, kilitleme açma, YZ tahminleri, adil piyango, 1xBet bonusları ve cüzdan takibi üzerine adım adım rehberler.',
    pt: 'Guias passo a passo sobre compensação, desbloqueio, previsões de IA, loteria justa, bônus 1xBet e acompanhamento de carteiras.',
  },
  'hub.companies_note': {
    ar: 'انقر على أي شركة لعرض صفحة التعويض الكاملة والكود الترويجي.',
    en: 'Click any company for its full compensation page and promo code.',
    es: 'Haz clic en cualquier empresa para ver su página completa de compensación y código promocional.',
    ru: 'Нажмите на компанию, чтобы открыть полную страницу компенсации и промокод.',
    fr: 'Cliquez sur une société pour voir sa page complète et son code promo.',
    de: 'Klicke auf ein Unternehmen für die vollständige Erstattungsseite und den Promo-Code.',
    tr: 'Herhangi bir şirkete tıklayarak tam tazminat sayfasını ve promosyon kodunu görün.',
    pt: 'Clique em qualquer empresa para ver sua página completa de compensação e código promocional.',
  },


  // ---------- Predictions list ----------
  'pred.list_h1': { ar: 'توقعات المباريات بالذكاء الاصطناعي', en: 'AI Football Match Predictions', es: 'Predicciones de fútbol con IA', ru: 'AI-прогнозы футбольных матчей', fr: 'Prédictions de football par IA', de: 'KI-Fußballspielprognosen', tr: 'Yapay Zeka Futbol Maç Tahminleri', pt: 'Previsões de futebol com IA' },
  'pred.list_desc': { ar: 'توقعات مباريات اليوم والغد بالذكاء الاصطناعي: احتمالات فوز، نتائج متوقعة، وتحليلات تكتيكيّة لأفضل الدوريات على {brand}.', en: 'AI predictions for today and tomorrow\'s matches: win probabilities, predicted scores, and tactical analysis of top leagues on {brand}.', es: 'Predicciones de IA para los partidos de hoy y mañana: probabilidades de victoria, resultados previstos y análisis táctico de las mejores ligas en {brand}.', ru: 'AI-прогнозы матчей сегодня и завтра: вероятности побед, прогнозы счета и тактический анализ топ-лиг на {brand}.', fr: 'Prédictions IA pour les matchs d’aujourd’hui et de demain : probabilités de victoire, scores prévus et analyse tactique des grands championnats sur {brand}.', de: 'KI-Prognosen für heute und morgen: Siegwahrscheinlichkeiten, TorgPrognosen und taktische Analysen der Top-Ligen auf {brand}.', tr: '{brand} üzerinde bugün ve yarınki maçlar için YZ tahminleri: kazanma olasılıkları, skor tahminleri ve üst liglerin taktik analizleri.', pt: 'Previsões de IA para os jogos de hoje e amanhã: probabilidades de vitória, placares previstos e análise tática das principais ligas na {brand}.' },
  'pred.today_h1': { ar: 'توقعات اليوم', en: "Today's AI Predictions", es: 'Predicciones de IA de hoy', ru: 'Прогнозы на сегодня', fr: "Prédictions IA d'aujourd'hui", de: 'KI-Prognosen für heute', tr: 'Bugünün YZ Tahminleri', pt: 'Previsões de IA de hoje' },
  'pred.tomorrow_h1': { ar: 'توقعات الغد', en: "Tomorrow's AI Predictions", es: 'Predicciones de IA de mañana', ru: 'Прогнозы на завтра', fr: 'Prédictions IA de demain', de: 'KI-Prognosen für morgen', tr: 'Yarının YZ Tahminleri', pt: 'Previsões de IA de amanhã' },
  'pred.day_h1': { ar: 'توقعات يوم', en: 'AI Predictions for', es: 'Predicciones de IA del', ru: 'Прогнозы на', fr: 'Prédictions IA du', de: 'KI-Prognosen für den', tr: 'Tahminler:', pt: 'Previsões de IA do dia' },
  'pred.day_desc': { ar: 'احتمالات الفوز والنتائج المتوقعة وتحليلات تكتيكيّة لمباريات {date} على {brand}.', en: 'Win probabilities, predicted scores and tactical analysis for every match on {date} — {brand}.', es: 'Probabilidades de victoria, resultados previstos y análisis táctico de todos los partidos del {date} — {brand}.', ru: 'Вероятности побед, прогнозы счёта и тактический анализ всех матчей {date} — {brand}.', fr: 'Probabilités de victoire, scores prévus et analyse tactique de tous les matchs du {date} — {brand}.', de: 'Siegwahrscheinlichkeiten, TorgPrognosen und taktische Analyse aller Spiele am {date} — {brand}.', tr: '{date} tarihli tüm maçlar için kazanma olasılıkları, skor tahminleri ve taktik analiz — {brand}.', pt: 'Probabilidades de vitória, placares previstos e análise tática de todos os jogos de {date} — {brand}.' },
  'pred.league_h1': { ar: 'توقعات {league}', en: '{league} Predictions', es: 'Predicciones de {league}', ru: 'Прогнозы: {league}', fr: 'Prédictions {league}', de: '{league} Prognosen', tr: '{league} Tahminleri', pt: 'Previsões {league}' },
  'pred.league_desc': { ar: 'احتمالات الفوز والنتائج المتوقعة وتحليلات تكتيكيّة لمباريات {league} هذا الأسبوع — على {brand}.', en: 'Win probabilities, predicted scores and tactical analysis for this week\'s {league} matches — on {brand}.', es: 'Probabilidades de victoria, resultados previstos y análisis táctico de los partidos de {league} esta semana — en {brand}.', ru: 'Вероятности побед, прогнозы счёта и тактический анализ матчей {league} на этой неделе — на {brand}.', fr: 'Probabilités de victoire, scores prévus et analyse tactique des matchs de {league} cette semaine — sur {brand}.', de: 'Siegwahrscheinlichkeiten, TorgPrognosen und taktische Analyse der {league}-Spiele diese Woche — bei {brand}.', tr: 'Bu haftanın {league} maçları için kazanma olasılıkları, skor tahminleri ve taktik analiz — {brand} üzerinde.', pt: 'Probabilidades de vitória, placares previstos e análise tática dos jogos da {league} nesta semana — em {brand}.' },
  'pred.team_h1': { ar: 'توقعات {team}', en: '{team} Predictions & Fixtures', es: 'Predicciones y partidos de {team}', ru: 'Прогнозы и матчи: {team}', fr: 'Prédictions et matchs de {team}', de: '{team} Prognosen & Spiele', tr: '{team} Tahminleri ve Fikstür', pt: 'Previsões e jogos do {team}' },
  'pred.team_desc': { ar: 'توقعات مباريات {team} القادمة: احتمالات الفوز، النتائج المتوقعة، وتحليل تكتيكي — على {brand}.', en: 'Upcoming {team} match predictions: win probabilities, predicted scores and tactical analysis — on {brand}.', es: 'Predicciones de los próximos partidos de {team}: probabilidades, resultados previstos y análisis táctico — en {brand}.', ru: 'Прогнозы на ближайшие матчи {team}: вероятности побед, прогнозы счёта и тактический анализ — на {brand}.', fr: 'Prédictions des prochains matchs de {team} : probabilités, scores prévus et analyse tactique — sur {brand}.', de: 'Prognosen für die nächsten {team}-Spiele: Siegwahrscheinlichkeiten, TorgPrognosen und taktische Analyse — bei {brand}.', tr: 'Yaklaşan {team} maç tahminleri: kazanma olasılıkları, skor tahminleri ve taktik analiz — {brand} üzerinde.', pt: 'Previsões dos próximos jogos do {team}: probabilidades de vitória, placares previstos e análise tática — em {brand}.' },
  'pred.rank_title': { ar: 'قوة الفرق في {league}', en: '{league} team power ranking', es: 'Ranking de equipos de {league}', ru: 'Рейтинг команд: {league}', fr: 'Classement des équipes : {league}', de: '{league} Team-Ranking', tr: '{league} takım güç sıralaması', pt: 'Ranking de equipes da {league}' },
  'link.best': { ar: 'أفضل المواقع', en: 'Best sites', es: 'Mejores sitios', ru: 'Лучшие сайты', fr: 'Meilleurs sites', de: 'Beste Seiten', tr: 'En iyi siteler', pt: 'Melhores sites' },
  'best.h1': { ar: 'أفضل مواقع المراهنات 2026 — أعلى {count} شركة موثوقة', en: 'Best Betting Sites 2026 — Top {count} Verified Bookmakers', es: 'Mejores casas de apuestas 2026 — Top {count} casas verificadas', ru: 'Лучшие букмекерские конторы 2026 — Топ {count} проверенных', fr: 'Meilleurs sites de paris 2026 — Top {count} bookmakers vérifiés', de: 'Beste Wettseiten 2026 — Top {count} geprüfte Buchmacher', tr: 'En iyi bahis siteleri 2026 — Doğrulanmış ilk {count} şirket', pt: 'Melhores casas de apostas 2026 — Top {count} casas verificadas' },
  'best.meta_desc': { ar: 'ترتيب أحدث مواقع المراهنات الموثوقة: البونص، أكواد الخصم، والتطبيق — محدّث على {brand}.', en: 'Ranking of the top trusted betting sites: welcome bonuses, promo codes and mobile apps — updated on {brand}.', es: 'Ranking de las mejores casas de apuestas de confianza: bonos, códigos y app móvil — actualizado en {brand}.', ru: 'Рейтинг лучших надёжных букмекеров: бонусы, промокоды и мобильное приложение — обновлено на {brand}.', fr: 'Classement des meilleurs sites de paris fiables : bonus, codes promo et app mobile — mis à jour sur {brand}.', de: 'Ranking der besten zuverlässigen Wettseiten: Boni, Promo-Codes und Mobile App — aktualisiert bei {brand}.', tr: 'Güvenilir en iyi bahis siteleri sıralaması: bonus, promosyon kodu ve mobil uygulama — {brand} üzerinde güncel.', pt: 'Ranking das melhores casas de apostas confiáveis: bônus, códigos e app mobile — atualizado em {brand}.' },
  'best.intro': { ar: 'اختر موقعك بثقة: قارنّا كل شركة مدعومة في {brand} حسب البونص، كود الخصم، وتجربة الجوال — والروابط أدناه شريكة ومحدّثة.', en: 'Pick your site with confidence: we compared every bookmaker supported on {brand} by bonus, promo code and mobile experience — the links below are current partner links.', es: 'Elige con confianza: comparamos cada casa admitida en {brand} por bono, código y experiencia móvil — los enlaces de abajo son enlaces de socios actualizados.', ru: 'Выбирайте уверенно: мы сравнили каждого букмекера на {brand} по бонусу, промокоду и мобильному удобству — ссылки ниже актуальные партнёрские.', fr: 'Choisissez en confiance : nous avons comparé chaque bookmaker de {brand} selon bonus, code promo et mobile — les liens ci-dessous sont des liens partenaires à jour.', de: 'Wählen Sie sicher: Wir haben jeden Anbieter bei {brand} nach Bonus, Promo-Code und Mobile verglichen — die Links unten sind aktuelle Partnerlinks.', tr: '{brand} üzerindeki her şirketi bonus, promosyon kodu ve mobil deneyime göre karşılaştırdık — aşağıdaki bağlantılar güncel ortak bağlantılarıdır.', pt: 'Escolha com confiança: comparamos cada casa de {brand} por bônus, código e experiência mobile — os links abaixo são links de parceiros atualizados.' },
  'best.rank_title': { ar: 'ترتيبنا لهذا العام', en: 'Our 2026 ranking', es: 'Nuestro ranking 2026', ru: 'Наш рейтинг 2026', fr: 'Notre classement 2026', de: 'Unser Ranking 2026', tr: '2026 sıralamamız', pt: 'Nosso ranking 2026' },
  'best.updated': { ar: 'محدّث:', en: 'Updated:', es: 'Actualizado:', ru: 'Обновлено:', fr: 'Mis à jour :', de: 'Aktualisiert:', tr: 'Güncelleme:', pt: 'Atualizado:' },
  'best.faq1q': { ar: 'ما أفضل موقع مراهنات في 2026؟', en: 'What is the best betting site in 2026?', es: '¿Cuál es la mejor casa de apuestas en 2026?', ru: 'Какая букмекерская контора лучшая в 2026?', fr: 'Quel est le meilleur site de paris en 2026 ?', de: 'Welche ist die beste Wettseite 2026?', tr: '2026’da en iyi bahis sitesi hangisi?', pt: 'Qual é a melhor casa de apostas em 2026?' },
  'best.faq1a': { ar: 'الترتيب مبني على البونص، سرعة السحب، والتطبيق — كل الشركات المدرجة موثوقة وتعمل عبر {brand}؛ قارن العروض واختر ما يناسبك.', en: 'The ranking weighs bonuses, withdrawal speed and mobile apps — every listed site is trusted and works with {brand}; compare the offers and pick your fit.', es: 'El ranking considera bonos, velocidad de retiro y app móvil — todos los sitios listados son fiables y funcionan con {brand}; compara y elige.', ru: 'Рейтинг учитывает бонусы, скорость вывода и приложение — все указанные сайты надёжны и работают с {brand}; сравните и выберите.', fr: 'Le classement pondère bonus, rapidité des retraits et app mobile — tous les sites listés sont fiables et fonctionnent avec {brand}.', de: 'Das Ranking gewichtet Bonus, Auszahlungsgeschwindigkeit und App — alle gelisteten Seiten sind zuverlässig und funktionieren mit {brand}.', tr: 'Sıralama bonus, çekim hızını ve uygulamayı değerlendirir — listelenen tüm siteler güvenilirdir ve {brand} ile çalışır.', pt: 'O ranking considera bônus, velocidade de saque e app — todos os sites listados são confiáveis e funcionam com {brand}.' },
  'best.faq2q': { ar: 'كيف تختارون الشركات في القائمة؟', en: 'How do you choose the sites on this list?', es: '¿Cómo eligen los sitios de esta lista?', ru: 'Как выбираются сайты в список?', fr: 'Comment choisissez-vous les sites de cette liste ?', de: 'Wie wählen Sie die Seiten für diese Liste?', tr: 'Bu listedeki siteleri nasıl seçiyorsunuz?', pt: 'Como vocês escolhem os sites desta lista?' },
  'best.faq2a': { ar: 'نراجع الترخيص، خيارات السحب، جودة التطبيق، ودعم اللغات — ونحدّث القائمة دورياً عند تغيّر العروض.', en: 'We review licensing, withdrawal options, app quality and language support — and refresh the list whenever offers change.', es: 'Revisamos licencia, retiros, calidad de la app e idiomas — y actualizamos la lista cuando cambian las ofertas.', ru: 'Мы проверяем лицензию, способы вывода, качество приложения и языки — и обновляем список при изменении предложений.', fr: 'Nous vérifions licence, retraits, qualité de l app et langues — et mettons à jour la liste quand les offres changent.', de: 'Wir prüfen Lizenz, Auszahlungen, App-Qualität und Sprachen — und aktualisieren die Liste bei Angebotänderungen.', tr: 'Lisansı, çekim seçeneklerini, uygulama kalitesini ve dilleri inceliyoruz — teklifler değişince listeyi güncelleriz.', pt: 'Verificamos licença, saques, qualidade do app e idiomas — e atualizamos a lista quando as ofertas mudam.' },
  'best.faq3q': { ar: 'هل المواقع في القائمة آمنة؟', en: 'Are the sites on this list safe?', es: '¿Son seguros los sitios de esta lista?', ru: 'Безопасны ли сайты из списка?', fr: 'Les sites de cette liste sont-ils sûrs ?', de: 'Sind die Seiten auf dieser Liste sicher?', tr: 'Bu listedeki siteler güvenli mi?', pt: 'Os sites desta lista são seguros?' },
  'best.faq3a': { ar: 'جميعها مذكورة بمحدّثات داخل {brand} وتعمل عبر روابط شركائنا — لكن تحقّق دائماً من الترخيص والشروط قبل الإيداع.', en: 'All of them are listed with current data inside {brand} through our partner links — but always verify the license and terms before depositing.', es: 'Todas están listadas con datos actualizados dentro de {brand} con nuestros enlaces de socios — pero verifica licencia y condiciones antes de depositar.', ru: 'Все они указаны с актуальными данными внутри {brand} — через партнёрские ссылки, но всегда проверяйте лицензию и условия перед депозитом.', fr: 'Toutes sont listées avec des données à jour dans {brand} via nos liens partenaires — vérifiez toujours licence et conditions avant dépôt.', de: 'Alle sind mit aktuellen Daten in {brand} über unsere Partnerlinks aufgeführt — prüfen Sie immer Lizenz und Bedingungen vor Einzahlung.', tr: 'Tümü {brand} içinde güncel verilerle ve ortak bağlantılarımızla listelenir — yatırım öncesi lisans ve koşulları her zaman doğrulayın.', pt: 'Todas são listadas com dados atualizados em {brand} pelos nossos links de parceiros — mas confira licença e termos antes de depositar.' },
  'pred.list_note': { ar: 'كل صفحة توقعات تحتوي على احتمالات فوز، النتيجة المتوقعة، وتحليل تكتيكي — محدّث يومياً لأفضل الدوريات في العالم.', en: 'Each prediction page includes win probabilities, a predicted score, and a tactical analysis — updated daily for the world\'s top leagues.', es: 'Cada página de predicciones incluye probabilidades de victoria, resultado previsto y análisis táctico — actualizado a diario para las mejores ligas.', ru: 'Каждая страница прогнозов содержит вероятности побед, прогноз счёта и тактический анализ — обновляется ежедневно для топ-лиг мира.', fr: 'Chaque page de prédictions contient les probabilités de victoire, un score prévu et une analyse tactique — mise à jour chaque jour pour les grands championnats.', de: 'Jede Prognoseseite enthält Siegwahrscheinlichkeiten, eine TorgPrognose und eine taktische Analyse — täglich aktualisiert für die Top-Ligen.', tr: 'Her tahmin sayfası kazanma olasılıkları, skor tahmini ve taktik analiz içerir — dünyanın en üst ligleri için her gün güncellenir.', pt: 'Cada página de previsões traz probabilidades de vitória, placar previsto e análise tática — atualizada diariamente para as melhores ligas.' },
  'pred.updated_note': { ar: 'محدّث يومياً', en: 'Updated daily', es: 'Actualizado a diario', ru: 'Обновляется ежедневно', fr: 'Mis à jour chaque jour', de: 'Täglich aktualisiert', tr: 'Her gün güncellenir', pt: 'Atualizado diariamente' },
  'pred.kickoff': { ar: 'انطلاق', en: 'Kick-off', es: 'Inicio', ru: 'Начало', fr: 'Coup d’envoi', de: 'Anstoß', tr: 'Başlangıç', pt: 'Início' },
  'pred.ai_badge': { ar: 'Gemini AI', en: 'Gemini AI', es: 'Gemini AI', ru: 'Gemini AI', fr: 'Gemini AI', de: 'Gemini AI', tr: 'Gemini AI', pt: 'Gemini AI' },

  // ---------- Predictions detail ----------
  'pred.probs_title': { ar: 'احتمالات المباراة', en: 'Match Probabilities', es: 'Probabilidades del partido', ru: 'Вероятности матча', fr: 'Probabilités du match', de: 'Spielwahrscheinlichkeiten', tr: 'Maç Olasılıkları', pt: 'Probabilidades do jogo' },
  'pred.prob_home': { ar: 'فوز {team}', en: '{team} win', es: 'Victoria de {team}', ru: 'Победа {team}', fr: 'Victoire de {team}', de: 'Sieg {team}', tr: '{team} galibiyeti', pt: 'Vitória do(a) {team}' },
  'pred.prob_draw': { ar: 'تعادل', en: 'Draw', es: 'Empate', ru: 'Ничья', fr: 'Match nul', de: 'Unentschieden', tr: 'Beraberlik', pt: 'Empate' },
  'pred.prob_away': { ar: 'فوز {team}', en: '{team} win', es: 'Victoria de {team}', ru: 'Победа {team}', fr: 'Victoire de {team}', de: 'Sieg {team}', tr: '{team} galibiyeti', pt: 'Vitória do(a) {team}' },
  'pred.score': { ar: 'النتيجة المتوقعة', en: 'Predicted Score', es: 'Resultado previsto', ru: 'Прогнозируемый счёт', fr: 'Score prévu', de: 'TorgPrognose', tr: 'Tahmini Skor', pt: 'Placar previsto' },
  'pred.analysis': { ar: 'التحليل التكتيكي', en: 'Tactical Analysis', es: 'Análisis táctico', ru: 'Тактический анализ', fr: 'Analyse tactique', de: 'Taktische Analyse', tr: 'Taktik Analiz', pt: 'Análise tática' },
  'pred.recommendation': { ar: 'التوصية', en: 'Recommendation', es: 'Recomendación', ru: 'Рекомендация', fr: 'Recommandation', de: 'Empfehlung', tr: 'Öneri', pt: 'Recomendação' },
  'pred.risk': { ar: 'مستوى المخاطرة', en: 'Risk Level', es: 'Nivel de riesgo', ru: 'Уровень риска', fr: 'Niveau de risque', de: 'Risikostufe', tr: 'Risk Seviyesi', pt: 'Nível de risco' },
  'pred.confidence': { ar: 'مؤشر الثقة', en: 'Confidence Score', es: 'Índice de confianza', ru: 'Уверенность', fr: 'Indice de confiance', de: 'Konfidenzwert', tr: 'Güven Skoru', pt: 'Índice de confiança' },
  'pred.ratings': { ar: 'تصنيف الفريقين', en: 'Team Ratings', es: 'Clasificaciones de equipos', ru: 'Рейтинги команд', fr: 'Classements des équipes', de: 'Team-Bewertungen', tr: 'Takım Sıralamaları', pt: 'Classificações das equipes' },
  'pred.faq1q': { ar: 'من هو المرشح للفوز في {home} ضد {away}؟', en: 'Who is favored to win {home} vs {away}?', es: '¿Quién es favorito en {home} contra {away}?', ru: 'Кто фаворит в матче {home} против {away}?', fr: 'Qui est favori entre {home} et {away} ?', de: 'Wer ist Favorit bei {home} gegen {away}?', tr: '{home} - {away} maçında favori kim?', pt: 'Quem é favorito em {home} x {away}?' },
  'pred.faq2q': { ar: 'ما هي النتيجة المتوقعة لمباراة {home} ضد {away}؟', en: 'What is the predicted score for {home} vs {away}?', es: '¿Cuál es el resultado previsto de {home} contra {away}?', ru: 'Какой прогнозируемый счёт в матче {home} против {away}?', fr: 'Quel est le score prévu pour {home} contre {away} ?', de: 'Wie lautet die TorgPrognose für {home} gegen {away}?', tr: '{home} - {away} maçı için tahmini skor nedir?', pt: 'Qual é o placar previsto para {home} x {away}?' },
  'pred.faq3q': { ar: 'ما مستوى المخاطرة في توقع {home} ضد {away}؟', en: 'What is the risk level for the {home} vs {away} prediction?', es: '¿Cuál es el nivel de riesgo de la predicción {home} contra {away}?', ru: 'Каков уровень риска прогноза {home} против {away}?', fr: 'Quel est le niveau de risque de la prévision {home} contre {away} ?', de: 'Wie hoch ist das Risiko der Prognose {home} gegen {away}?', tr: '{home} - {away} tahmini için risk seviyesi nedir?', pt: 'Qual é o nível de risco da previsão {home} x {away}?' },
  'pred.related': { ar: 'توقعات ذات صلة', en: 'Related Predictions', es: 'Predicciones relacionadas', ru: 'Похожие прогнозы', fr: 'Prédictions associées', de: 'Ähnliche Prognosen', tr: 'İlgili Tahminler', pt: 'Previsões relacionadas' },
  'pred.cta_all': { ar: 'كل التوقعات', en: 'All Predictions', es: 'Todas las predicciones', ru: 'Все прогнозы', fr: 'Toutes les prédictions', de: 'Alle Prognosen', tr: 'Tüm Tahminler', pt: 'Todas as previsões' },
  'pred.cta_guide': { ar: 'دليل قراءة التوقعات', en: 'How to Read Predictions', es: 'Cómo leer las predicciones', ru: 'Как читать прогнозы', fr: 'Comment lire les prédictions', de: 'Prognosen richtig lesen', tr: 'Tahminleri Okuma Rehberi', pt: 'Como ler as previsões' },
  'pred.breadcrumb': { ar: 'توقعات المباريات', en: 'Match Predictions', es: 'Predicciones de partidos', ru: 'Прогнозы матчей', fr: 'Prédictions de matchs', de: 'Spielprognosen', tr: 'Maç Tahminleri', pt: 'Previsões de jogos' },
};

export function t(key: string, lang: Lang, vars?: Record<string, string>): string {
  const row = T[key];
  let s = row ? (row[lang] || row['ar'] || '') : '';
  if (vars) for (const [k, v] of Object.entries(vars)) s = s.split(`{${k}}`).join(v);
  return s;
}

// Extra chrome keys (added separately to keep the main table readable)
const T2: Record<string, Row> = {
  'nav.home': { ar: 'الرئيسية', en: 'Home', es: 'Inicio', ru: 'Главная', fr: 'Accueil', de: 'Start', tr: 'Ana Sayfa', pt: 'Início' },
  'nav.companies': { ar: 'الشركات', en: 'Companies', es: 'Compañías', ru: 'Компании', fr: 'Sociétés', de: 'Unternehmen', tr: 'Şirketler', pt: 'Empresas' },
  'nav.wallets': { ar: 'المحافظ', en: 'Wallets', es: 'Carteras', ru: 'Кошельки', fr: 'Portefeuilles', de: 'Wallets', tr: 'Cüzdanlar', pt: 'Carteiras' },
  'nav.predictions': { ar: 'التوقعات', en: 'Predictions', es: 'Predicciones', ru: 'Прогнозы', fr: 'Prédictions', de: 'Prognosen', tr: 'Tahminler', pt: 'Previsões' },
  'nav.lottery': { ar: 'اليانصيب', en: 'Lottery', es: 'Lotería', ru: 'Лотерея', fr: 'Loterie', de: 'Lotto', tr: 'Piyango', pt: 'Loteria' },
  'nav.download': { ar: 'تحميل APK', en: 'Download APK', es: 'Descargar APK', ru: 'Скачать APK', fr: 'Télécharger l’APK', de: 'APK herunterladen', tr: 'APK İndir', pt: 'Baixar APK' },
  'faq.q_prefix': { ar: 'س:', en: 'Q:', es: 'P:', ru: 'В:', fr: 'Q :', de: 'F:', tr: 'S:', pt: 'P:' },
  'company.footer_page': { ar: 'صفحة {name} — آخر تحديث:', en: 'Page for {name} — last updated:', es: 'Página de {name} — última actualización:', ru: 'Страница {name} — последнее обновление:', fr: 'Page {name} — dernière mise à jour :', de: 'Seite für {name} — zuletzt aktualisiert:', tr: '{name} sayfası — son güncelleme:', pt: 'Página da {name} — última atualização:' },
  'company.updated_only': { ar: 'آخر تحديث:', en: 'Last updated:', es: 'Última actualización:', ru: 'Последнее обновление:', fr: 'Dernière mise à jour :', de: 'Zuletzt aktualisiert:', tr: 'Son güncelleme:', pt: 'Última atualização:' },
  'pred.qa_prefix': { ar: 'س:', en: 'Q:', es: 'P:', ru: 'В:', fr: 'Q :', de: 'F:', tr: 'S:', pt: 'P:' },
  'pred.faq_risk_note': { ar: 'ثقة {confidence}% والتوصية: {pick}', en: 'confidence {confidence}% and recommendation: {pick}', es: 'confianza {confidence}% y recomendación: {pick}', ru: 'уверенность {confidence}% и рекомендация: {pick}', fr: 'confiance {confidence} % et recommandation : {pick}', de: 'Konfidenz {confidence} % und Empfehlung: {pick}', tr: 'güven {confidence}% ve öneri: {pick}', pt: 'confiança {confidence}% e recomendação: {pick}' },
  'pred.fav_note': { ar: 'الترجيح يميل لـ {favorite} بنسبة {prob}%', en: 'The edge favors {favorite} at {prob}%', es: 'La ventaja favorece a {favorite} con un {prob}%', ru: 'Преимущество у {favorite} с {prob}%', fr: 'L’avantage va à {favorite} à {prob}%', de: 'Der Vorteil liegt bei {favorite} mit {prob}%', tr: 'Avantaj {favorite} lehine % {prob}', pt: 'A vantagem é de {favorite} com {prob}%' },
  'pred.draw_note': { ar: 'النتيجة المتوقعة {score} لصالح {favorite}.', en: 'The predicted score is {score} in favor of {favorite}.', es: 'El resultado previsto es {score} a favor de {favorite}.', ru: 'Прогнозируемый счёт {score} в пользу {favorite}.', fr: 'Le score prévu est {score} en faveur de {favorite}.', de: 'Die TorgPrognose lautet {score} für {favorite}.', tr: 'Tahmini skor {favorite} lehine {score}.', pt: 'O placar previsto é {score} a favor do(a) {favorite}.' },
  'pred.reco_note': { ar: 'التوصية: {pick}', en: 'Recommendation: {pick}', es: 'Recomendación: {pick}', ru: 'Рекомендация: {pick}', fr: 'Recommandation : {pick}', de: 'Empfehlung: {pick}', tr: 'Öneri: {pick}', pt: 'Recomendação: {pick}' },
  'pred.risk_note': { ar: 'مستوى المخاطرة {risk}', en: 'Risk level {risk}', es: 'Nivel de riesgo {risk}', ru: 'Уровень риска {risk}', fr: 'Niveau de risque {risk}', de: 'Risikostufe {risk}', tr: 'Risk seviyesi {risk}', pt: 'Nível de risco {risk}' },
  'pred.preds_label': { ar: 'التوقعات', en: 'Predictions', es: 'Predicciones', ru: 'Прогнозы', fr: 'Prédictions', de: 'Prognosen', tr: 'Tahminler', pt: 'Previsões' },
  'risk.low': { ar: 'منخفضة', en: 'Low', es: 'Bajo', ru: 'Низкий', fr: 'Faible', de: 'Niedrig', tr: 'Düşük', pt: 'Baixo' },
  'risk.medium': { ar: 'متوسطة', en: 'Medium', es: 'Medio', ru: 'Средний', fr: 'Moyen', de: 'Mittel', tr: 'Orta', pt: 'Médio' },
  'risk.high': { ar: 'عالية', en: 'High', es: 'Alto', ru: 'Высокий', fr: 'Élevé', de: 'Hoch', tr: 'Yüksek', pt: 'Alto' },
  'pred.vs_note': { ar: '{home} ({hr}) مقابل {away} ({ar}) — {fav_note}، {score_note}', en: '{home} ({hr}) vs {away} ({ar}) — {fav_note}, {score_note}', es: '{home} ({hr}) contra {away} ({ar}) — {fav_note}, {score_note}', ru: '{home} ({hr}) против {away} ({ar}) — {fav_note}, {score_note}', fr: '{home} ({hr}) contre {away} ({ar}) — {fav_note}, {score_note}', de: '{home} ({hr}) gegen {away} ({ar}) — {fav_note}, {score_note}', tr: '{home} ({hr}) - {away} ({ar}) — {fav_note}, {score_note}', pt: '{home} ({hr}) x {away} ({ar}) — {fav_note}, {score_note}' },
  'pred.meta_desc': { ar: 'توقعات {home} ضد {away} بتاريخ {date}: احتمال الفوز {ph}% مقابل {pa}%، النتيجة المتوقعة {score}، وثقة {confidence}%.', en: 'Predictions for {home} vs {away} on {date}: {ph}% win probability vs {pa}%, predicted score {score}, confidence {confidence}%.', es: 'Predicciones de {home} contra {away} el {date}: {ph}% de probabilidad de victoria frente a {pa}%, resultado previsto {score}, confianza {confidence}%.', ru: 'Прогнозы {home} против {away} на {date}: вероятность победы {ph}% против {pa}%, прогноз счёта {score}, уверенность {confidence}%.', fr: 'Prédictions {home} contre {away} le {date} : {ph} % de probabilité de victoire contre {pa} %, score prévu {score}, confiance {confidence} %.', de: 'Prognosen für {home} gegen {away} am {date}: {ph} % Siegwahrscheinlichkeit gegenüber {pa} %, TorgPrognose {score}, Konfidenz {confidence} %.', tr: '{date} tarihli {home} - {away} tahminleri: {ph}% kazanma olasılığı - {pa}%, tahmini skor {score}, güven {confidence}%.', pt: 'Previsões de {home} x {away} em {date}: {ph}% de probabilidade de vitória contra {pa}%, placar previsto {score}, confiança {confidence}%.' },
  'pred.title_tpl': { ar: '{home} ضد {away} توقعات — {date} احتمالات ونتيجة متوقعة', en: '{home} vs {away} Predictions — {date} probabilities & predicted score', es: 'Predicciones de {home} contra {away} — {date}: probabilidades y resultado previsto', ru: 'Прогнозы {home} против {away} — {date}: вероятности и прогноз счёта', fr: 'Prédictions {home} contre {away} — {date} : probabilités et score prévu', de: '{home} gegen {away} Prognosen — {date}: Wahrscheinlichkeiten und TorgPrognose', tr: '{home} - {away} Tahminleri — {date}: olasılıklar ve tahmini skor', pt: 'Previsões de {home} x {away} — {date}: probabilidades e placar previsto' },
  'pred.og_desc': { ar: 'احتمال الفوز {ph}% مقابل {pa}% — النتيجة المتوقعة {score}', en: 'Win probability {ph}% vs {pa}% — predicted score {score}', es: 'Probabilidad de victoria {ph}% frente a {pa}% — resultado previsto {score}', ru: 'Вероятность победы {ph}% против {pa}% — прогноз счёта {score}', fr: 'Probabilité de victoire {ph} % contre {pa} % — score prévu {score}', de: 'Siegwahrscheinlichkeit {ph} % gegenüber {pa} % — TorgPrognose {score}', tr: 'Kazanma olasılığı {ph}% - {pa}% — tahmini skor {score}', pt: 'Probabilidade de vitória {ph}% contra {pa}% — placar previsto {score}' },
  // ---------- Comparison pages (programmatic SEO) ----------
  'link.compare': { ar: 'مقارنات الشركات', en: 'Bookmaker comparisons', es: 'Comparativas', ru: 'Сравнения', fr: 'Comparaisons', de: 'Vergleiche', tr: 'Karşılaştırmalar', pt: 'Comparações' },
  'cmp.hub_h1': { ar: 'مقارنة شركات المراهنات', en: 'Bookmaker Comparisons', es: 'Comparativas de casas de apuestas', ru: 'Сравнение букмекеров', fr: 'Comparaisons de bookmakers', de: 'Wettanbieter-Vergleiche', tr: 'Bahis Sitesi Karşılaştırmaları', pt: 'Comparações de casas de apostas' },
  'cmp.hub_desc': { ar: 'قارن شركات المراهنات المميزة جنباً إلى جنب: البونص، أكواد الخصم، والمزايا — على {brand}.', en: 'Compare top betting sites side by side: bonuses, promo codes and features — on {brand}.', es: 'Compara las mejores casas de apuestas lado a lado: bonos, códigos promocionales y características — en {brand}.', ru: 'Сравните лучшие букмекерские конторы: бонусы, промокоды и возможности — на {brand}.', fr: 'Comparez les meilleurs sites de paris côte à côte : bonus, codes promo et fonctionnalités — sur {brand}.', de: 'Vergleichen Sie die besten Wettanbieter direkt: Boni, Promo-Codes und Funktionen — bei {brand}.', tr: 'En iyi bahis sitelerini yan yana karşılaştırın: bonuslar, promosyon kodları ve özellikler — {brand} üzerinde.', pt: 'Compare as melhores casas de apostas lado a lado: bônus, códigos promocionais e recursos — em {brand}.' },
  'cmp.h1': { ar: '{a} مقابل {b} — أيهما أفضل 2026؟', en: '{a} vs {b} — Which Is Better in 2026?', es: '{a} vs {b} — ¿Cuál es mejor en 2026?', ru: '{a} vs {b} — что лучше в 2026 году?', fr: '{a} vs {b} — Lequel est le meilleur en 2026 ?', de: '{a} vs {b} — Was ist 2026 besser?', tr: '{a} vs {b} — 2026’da hangisi daha iyi?', pt: '{a} vs {b} — Qual é melhor em 2026?' },
  'cmp.meta_desc': { ar: 'مقارنة {a} و{b}: البونص، كود الترويج، تطبيق الجوال وسرعة السحب — اختر بذكاء على {brand}.', en: 'Comparing {a} vs {b}: welcome bonus, promo code, mobile app and withdrawal speed — choose wisely on {brand}.', es: 'Comparativa de {a} vs {b}: bono, código promocional, app móvil y retiros — elige bien en {brand}.', ru: 'Сравнение {a} и {b}: бонус, промокод, мобильное приложение и вывод средств — правильный выбор на {brand}.', fr: 'Comparaison {a} vs {b} : bonus, code promo, app mobile et retraits — choisissez bien sur {brand}.', de: 'Vergleich {a} vs {b}: Bonus, Promo-Code, Mobile App und Auszahlung — richtig entscheiden bei {brand}.', tr: '{a} vs {b} karşılaştırma: bonus, promosyon kodu, mobil uygulama ve çekim — {brand} üzerinde akıllıca seçin.', pt: 'Comparação de {a} vs {b}: bônus, código promocional, app mobile e saques — escolha bem em {brand}.' },
  'cmp.intro': { ar: 'قرّر بثقة بين {a} و{b}: قارنّا البونص والمزايا وتجربة الاستخدام لمساعدتك على الاختيار الأنسب لطريقتك وميزانيتك.', en: 'Decide with confidence between {a} and {b}: we compared bonuses, features and user experience to help you pick what fits your style and budget.', es: 'Decide con confianza entre {a} y {b}: comparamos bonos, características y experiencia de usuario para ayudarte a elegir.', ru: 'Выбирайте уверенно между {a} и {b}: мы сравнили бонусы, функции и удобство, чтобы помочь вам с выбором.', fr: 'Décidez en toute confiance entre {a} et {b} : nous avons comparé bonus, fonctionnalités et ergonomie pour vous guider.', de: 'Entscheiden Sie sich sicher zwischen {a} und {b}: Wir haben Boni, Funktionen und Benutzererfahrung verglichen.', tr: '{a} ile {b} arasında güvenle karar verin: bonusları, özellikleri ve kullanıcı deneyimini karşılaştırdık.', pt: 'Decida com confiança entre {a} e {b}: comparamos bônus, recursos e experiência do usuário para guiar você.' },
  'cmp.table_title': { ar: 'مقارنة سريعة', en: 'Quick comparison', es: 'Comparativa rápida', ru: 'Быстрое сравнение', fr: 'Comparaison rapide', de: 'Schneller Vergleich', tr: 'Hızlı karşılaştırma', pt: 'Comparação rápida' },
  'cmp.row_bonus': { ar: 'البونص', en: 'Welcome bonus', es: 'Bono de bienvenida', ru: 'Приветственный бонус', fr: 'Bonus de bienvenue', de: 'Willkommensbonus', tr: 'Hoş geldin bonusu', pt: 'Bônus de boas-vindas' },
  'cmp.row_promo': { ar: 'كود الخصم', en: 'Promo code', es: 'Código promocional', ru: 'Промокод', fr: 'Code promo', de: 'Promo-Code', tr: 'Promosyon kodu', pt: 'Código promocional' },
  'cmp.row_about': { ar: 'نبذة', en: 'About', es: 'Acerca de', ru: 'О компании', fr: 'À propos', de: 'Über', tr: 'Hakkında', pt: 'Sobre' },
  'cmp.row_app': { ar: 'تطبيق الجوال', en: 'Mobile app', es: 'App móvil', ru: 'Мобильное приложение', fr: 'Application mobile', de: 'Mobile App', tr: 'Mobil uygulama', pt: 'App mobile' },
  'cmp.verdict_title': { ar: 'الخلاصة', en: 'Verdict', es: 'Veredicto', ru: 'Вердикт', fr: 'Verdict', de: 'Fazit', tr: 'Sonuç', pt: 'Veredito' },
  'cmp.verdict': { ar: 'لا يوجد فائز مطلق: {a} و{b} كلاهما خيار قوي. استخدم جدول المقارنة أعلاه ثم اختر ما يناسب أسلوب لعبك وميزانيتك.', en: 'There is no single winner: both {a} and {b} are strong choices. Use the comparison table above, then pick what suits your play style and budget.', es: 'No hay un ganador único: tanto {a} como {b} son buenas opciones. Usa la tabla de arriba y elige según tu estilo y presupuesto.', ru: 'Абсолютного победителя нет: и {a}, и {b} — хороший выбор. Используйте таблицу выше и выбирайте под свой стиль и бюджет.', fr: 'Il ny a pas de vainqueur unique : {a} et {b} sont tous deux de bons choix. Utilisez le tableau ci-dessus selon votre style et budget.', de: 'Es gibt keinen klaren Gewinner: {a} und {b} sind beide gute Wahl. Nutzen Sie die Tabelle oben passend zu Stil und Budget.', tr: 'Tek bir kazanan yok: hem {a} hem {b} güçlü seçenekler. Yukarıdaki tabloyu kullanın, üslubunuza ve bütçenize göre seçin.', pt: 'Não há um vencedor único: {a} e {b} são boas escolhas. Use a tabela acima e escolha conforme seu estilo e orçamento.' },
  'cmp.faq1q': { ar: 'أيهما أفضل {a} أم {b}؟', en: 'Which is better, {a} or {b}?', es: '¿Cuál es mejor, {a} o {b}?', ru: 'Что лучше: {a} или {b}?', fr: 'Quel est le meilleur, {a} ou {b} ?', de: 'Was ist besser, {a} oder {b}?', tr: 'Hangisi daha iyi: {a} mı {b} mi?', pt: 'Qual é melhor, {a} ou {b}?' },
  'cmp.faq1a': { ar: 'كلاهما شركة موثوقة بمزايا متشابهة — قارن البونص وكود الخصم في الجدول بالأعلى ثم اختر ما يناسبك.', en: 'Both are established bookmakers with a similar feature set — compare their welcome bonus and promo code in the table above, then decide.', es: 'Ambas son casas consolidadas con funciones similares — compara bono y código en la tabla de arriba y decide.', ru: 'Обе конторы с похожим набором функций — сравните бонус и промокод в таблице выше и сделайте выбор.', fr: 'Ce sont deux opérateurs établis avec des fonctions similaires — comparez bonus et code promo dans le tableau ci-dessus.', de: 'Beide sind etablierte Anbieter mit ähnlichen Funktionen — vergleichen Sie Bonus und Promo-Code in der Tabelle oben.', tr: 'İkisi de benzer özelliklere sahip köklü şirketler — yukarıdaki tabloda bonusu ve kodu karşılaştırıp karar verin.', pt: 'Ambas são casas consolidadas com recursos semelhantes — compare bônus e código na tabela acima e decida.' },
  'cmp.faq2q': { ar: 'هل يوفّران تطبيق جوال {a} و{b}؟', en: 'Do {a} and {b} offer a mobile app?', es: '¿Ofrecen app móvil {a} y {b}?', ru: 'Есть ли мобильные приложения у {a} и {b}?', fr: '{a} et {b} proposent-ils une application mobile ?', de: 'Bieten {a} und {b} eine Mobile App?', tr: '{a} ve {b} mobil uygulama sunuyor mu?', pt: '{a} e {b} oferecem app mobile?' },
  'cmp.faq2a': { ar: 'نعم — كلاهما متاح على الجوال عبر APK لأندرويد والموقع المحمول، وتجد الرابط في صفحة كل شركة.', en: 'Yes — both work on mobile via the Android APK and the mobile site; the link is on each company page.', es: 'Sí — ambas funcionan en móvil con el APK de Android y la web móvil; el enlace está en cada página.', ru: 'Да — обе доступны на мобильном через APK для Android и мобильный сайт; ссылка на странице каждой компании.', fr: 'Oui — les deux fonctionnent sur mobile via l APK Android et le site mobile ; le lien est sur chaque page.', de: 'Ja — beide funktionieren mobil über die Android-APK und die mobile Website; der Link steht auf jeder Unternehmensseite.', tr: 'Evet — ikisi de Android APK ve mobil site ile çalışır; bağlantı her şirket sayfasında.', pt: 'Sim — ambas funcionam no mobile pelo APK Android e pelo site mobile; o link está em cada página.' },
  'cmp.faq3q': { ar: 'كيف أسجّل في {a} أو {b}؟', en: 'How do I register on {a} or {b}?', es: '¿Cómo me registro en {a} o {b}?', ru: 'Как зарегистрироваться в {a} или {b}?', fr: 'Comment m’inscrire sur {a} ou {b} ?', de: 'Wie registriere ich mich bei {a} oder {b}?', tr: '{a} veya {b}’ye nasıl kayıt olurum?', pt: 'Como me registro no {a} ou no {b}?' },
  'cmp.faq3a': { ar: 'افتح صفحة الشركة من الروابط، استخدم كود الترويج أثناء التسجيل، ثم تحقّق من حسابك — الخطوات الكاملة في الأدلة.', en: 'Open the company page from the links, use the promo code during registration, then verify your account — full steps are in our Guides.', es: 'Abre la página de la empresa desde los enlaces, usa el código al registrarte y verifica tu cuenta — pasos completos en las Guías.', ru: 'Откройте страницу компании по ссылке, используйте промокод при регистрации и подтвердите аккаунт — подробные шаги в разделе Гайдов.', fr: 'Ouvrez la page de la société depuis les liens, utilisez le code promo à l inscription puis vérifiez votre compte — étapes complètes dans les Guides.', de: 'Öffnen Sie die Unternehmensseite über die Links, verwenden Sie den Promo-Code bei der Registrierung und verifizieren Sie das Konto — alle Schritte in den Guides.', tr: 'Bağlantılardan şirket sayfasını açın, kayıt sırasında promosyon kodunu kullanın ve hesabınızı doğrulayın — tüm adımlar Rehberlerde.', pt: 'Abra a página da empresa pelos links, use o código promocional no registro e verifique sua conta — passos completos nos Guias.' },
  'cmp.more_title': { ar: 'مقارنات أخرى', en: 'More comparisons', es: 'Más comparativas', ru: 'Ещё сравнения', fr: 'Plus de comparaisons', de: 'Weitere Vergleiche', tr: 'Daha fazla karşılaştırma', pt: 'Mais comparações' },
  'cmp.cta_visit': { ar: 'زيارة {name}', en: 'Visit {name}', es: 'Visitar {name}', ru: 'Перейти: {name}', fr: 'Voir {name}', de: '{name} besuchen', tr: '{name}’i ziyaret et', pt: 'Visitar {name}' },

  // ---------- Homepage visible FAQ (shown in SSR SEO block) ----------
  'home.faq_title': { ar: 'الأسئلة الشائعة', en: 'Frequently Asked Questions', es: 'Preguntas frecuentes', ru: 'Частые вопросы', fr: 'Questions fréquentes', de: 'Häufige Fragen', tr: 'Sık Sorulan Sorular', pt: 'Perguntas frequentes' },
  'home.faq1q': { ar: 'كيف يعمل تعويض الخسائر؟', en: 'How does loss compensation work?', es: '¿Cómo funciona la compensación de pérdidas?', ru: 'Как работает компенсация проигрышей?', fr: 'Comment fonctionne l’indemnisation des pertes ?', de: 'Wie funktioniert die Verlusterstattung?', tr: 'Kayıp tazminatı nasıl çalışır?', pt: 'Como funciona a compensação de perdas?' },
  'home.faq1a': { ar: 'سجّل عبر روابط شركائنا وتابع نشاطك؛ تقدّم طلب تعويض مع إثباتات، وتُضاف النسب المؤهّلة إلى رصيدك وفق شروط كل برنامج.', en: 'Register through our partner links and track your activity; submit a compensation request with proof, and eligible percentages are added to your balance under each program’s terms.', es: 'Regístrate a través de nuestros enlaces de socios y sigue tu actividad; envía una solicitud de compensación con pruebas y los porcentajes elegibles se añaden a tu saldo según las condiciones de cada programa.', ru: 'Регистрируйтесь по партнёрским ссылкам и отслеживайте активность; отправьте запрос на компенсацию с подтверждениями — подходящие проценты добавятся к балансу по условиям программы.', fr: 'Inscrivez-vous via nos liens partenaires et suivez votre activité ; envoyez une demande d’indemnisation avec justificatifs — les pourcentages éligibles sont ajoutés à votre solde selon les conditions du programme.', de: 'Registrieren Sie sich über unsere Partnerlinks und verfolgen Sie Ihre Aktivität; reichen Sie einen Erstattungsantrag mit Nachweisen ein — berechtigte Prozente werden gemäß den Programmbedingungen gutgeschrieben.', tr: 'Ortak bağlantılarımızla kayıt olun ve aktivitenizi takip edin; kanıtlarla tazminat talebi gönderin — uygun yüzdeler program koşullarına göre bakiyenize eklenir.', pt: 'Registre-se pelos nossos links de parceiros e acompanhe sua atividade; envie um pedido de compensação com provas — os percentuais elegíveis entram no seu saldo conforme as condições de cada programa.' },
  'home.faq2q': { ar: 'كيف أفكّ تجميد الرصيد؟', en: 'How do I unfreeze a balance?', es: '¿Cómo desbloqueo un saldo?', ru: 'Как разморозить баланс?', fr: 'Comment débloquer un solde ?', de: 'Wie entsperre ich ein Guthaben?', tr: 'Bakiyeyi nasıl çözerim?', pt: 'Como descongelo um saldo?' },
  'home.faq2a': { ar: 'طريقتان: إيداع مباشر بنسبة 1:1 مع إثبات التحويل، أو نظام الإحالات حيث يُفك 10% عند قبول الصديق للتحويل وبدء نشاطه.', en: 'Two ways: a direct 1:1 deposit with transfer proof, or the referral system, where 10% unfreezes once your friend accepts the transfer and starts being active.', es: 'Dos vías: un depósito directo 1:1 con comprobante de transferencia, o el sistema de referidos, donde se desbloquea el 10% cuando tu amigo acepta la transferencia y comienza su actividad.', ru: 'Два способа: прямой депозит 1:1 с подтверждением перевода или реферальная система — 10% размораживаются, когда друг принимает перевод и начинает активность.', fr: 'Deux méthodes : un dépôt direct 1:1 avec justificatif de virement, ou le système de parrainage — 10 % sont débloqués lorsque votre ami accepte le virement et commence son activité.', de: 'Zwei Wege: eine direkte 1:1-Einzahlung mit Überweisungsnachweis oder das Empfehlungssystem — 10 % werden freigegeben, sobald Ihr Freund die Überweisung annimmt und aktiv wird.', tr: 'İki yol: dekontlu doğrudan 1:1 depozito veya referans sistemi — arkadaş transferi kabul edip aktif olduğunda %10 çözülür.', pt: 'Duas formas: depósito direto 1:1 com comprovante de transferência ou o sistema de indicações — 10% são descongelados quando seu amigo aceita a transferência e começa a atividade.' },
  'home.faq3q': { ar: 'هل اليانصيب قابل للتحقق من العدالة؟', en: 'Is the lottery provably fair?', es: '¿Es la lotería verificablemente justa?', ru: 'Лотерея честна и проверяема?', fr: 'La loterie est-elle vérifiablement équitable ?', de: 'Ist das Lotto nachweisbar fair?', tr: 'Piyango kanıtlanabilir adil mi?', pt: 'A loteria é comprovadamente justa?' },
  'home.faq3a': { ar: 'نعم — نستخدم تجزئة SHA-256 لبذرة الخادم مع بذرة العميل والعدّاد، و5 أرقام من 1 إلى 30، وسحوبات يمكن التحقق منها.', en: 'Yes — we use SHA-256 hashing of the server seed with client seed and nonce, 5 numbers from 1–30, and verifiable draws.', es: 'Sí — usamos hash SHA-256 de la semilla del servidor con semilla del cliente y nonce, 5 números del 1 al 30 y sorteos verificables.', ru: 'Да — мы используем хеширование SHA-256 серверного сида с клиентским сидом и nonce, 5 чисел от 1 до 30 и проверяемые розыгрыши.', fr: 'Oui — nous utilisons le hachage SHA-256 de la graine serveur avec graine client et nonce, 5 numéros de 1 à 30 et des tirages vérifiables.', de: 'Ja — wir verwenden SHA-256-Hashing des Serverseeds mit Clientseed und Nonce, 5 Zahlen von 1–30 und überprüfbare Ziehungen.', tr: 'Evet — sunucu tohumunun SHA-256 karmaşığı, istemci tohumu ve nonce; 1–30 arası 5 sayı; doğrulanabilir çekilişler.', pt: 'Sim — usamos hash SHA-256 da semente do servidor com semente do cliente e nonce, 5 números de 1 a 30 e sorteios verificáveis.' },
  'home.faq4q': { ar: 'كيف تعمل توقعات المباريات بالذكاء الاصطناعي؟', en: 'How do AI match predictions work?', es: '¿Cómo funcionan las predicciones con IA?', ru: 'Как работают AI-прогнозы матчей?', fr: 'Comment fonctionnent les prédictions de matchs par IA ?', de: 'Wie funktionieren KI-Spielprognosen?', tr: 'YZ maç tahminleri nasıl çalışır?', pt: 'Como funcionam as previsões de jogos com IA?' },
  'home.faq4a': { ar: 'محرك Gemini يحلّل إحصائيات الفرق والنتائج السابقة والأرقام، ويعيد احتمالات فوز ونتيجة متوقعة ومؤشر ثقة — توقعات احتمالية وليست ضماناً للنتيجة.', en: 'The Gemini engine analyzes team statistics, previous results and odds, returning win probabilities, a predicted score and a confidence score — probabilistic estimates, not guaranteed outcomes.', es: 'El motor Gemini analiza estadísticas, resultados anteriores y cuotas, y devuelve probabilidades de victoria, resultado previsto e índice de confianza — estimaciones probabilísticas, no resultados garantizados.', ru: 'Движок Gemini анализирует статистику команд, прошлые результаты и коэффициенты, возвращая вероятности побед, прогноз счёта и уровень уверенности — вероятностные оценки, а не гарантированный результат.', fr: 'Le moteur Gemini analyse les statistiques, les résultats passés et les cotes, et renvoie probabilités de victoire, score prévu et indice de confianza — des estimations probabilistes, pas des résultats garantis.', de: 'Die Gemini-Engine analysiert Teamstatistiken, frühere Ergebnisse und Quoten und liefert Siegwahrscheinlichkeiten, eine TorgPrognose und einen Konfidenzwert — Wahrscheinlichkeitsschätzungen, keine garantierten Ergebnisse.', tr: 'Gemini motoru takım istatistiklerini, geçmiş sonuçları ve oranları analiz eder; kazanma olasılıkları, skor tahmini ve güven skoru döndürür — olasılıksal tahminler, garanti sonuçlar değil.', pt: 'O motor Gemini analisa estatísticas, resultados anteriores e probabilidades, retornando chances de vitória, placar previsto e índice de confiança — estimativas probabilísticas, não resultados garantidos.' },

  // ---------- Trust / legal page labels ----------
  'trust.about': { ar: 'من نحن', en: 'About', es: 'Quiénes somos', ru: 'О нас', fr: 'À propos', de: 'Über uns', tr: 'Hakkımızda', pt: 'Sobre nós' },
  'trust.contact': { ar: 'اتصل بنا', en: 'Contact', es: 'Contacto', ru: 'Контакты', fr: 'Contact', de: 'Kontakt', tr: 'İletişim', pt: 'Contato' },
  'trust.privacy': { ar: 'سياسة الخصوصية', en: 'Privacy Policy', es: 'Política de privacidad', ru: 'Политика конфиденциальности', fr: 'Politique de confidentialité', de: 'Datenschutz', tr: 'Gizlilik Politikası', pt: 'Política de privacidade' },
  'trust.terms': { ar: 'الشروط والأحكام', en: 'Terms & Conditions', es: 'Términos y condiciones', ru: 'Условия использования', fr: 'Conditions générales', de: 'Nutzungsbedingungen', tr: 'Kullanım Şartları', pt: 'Termos e condições' },
  'trust.editorial': { ar: 'سياسة التحرير', en: 'Editorial Policy', es: 'Política editorial', ru: 'Редакционная политика', fr: 'Charte éditoriale', de: 'Redaktionslinien', tr: 'Editoryal Politika', pt: 'Política editorial' },
  'trust.affiliate': { ar: 'إفصاح الأطراف ذات العلاقة', en: 'Affiliate Disclosure', es: 'Divulgación de afiliados', ru: 'Раскрытие партнёрских ссылок', fr: 'Divulgation d’affiliation', de: 'Affiliate-Hinweis', tr: 'Ortaklık Açıklaması', pt: 'Divulgação de afiliados' },
  'trust.security': { ar: 'الأمان', en: 'Security', es: 'Seguridad', ru: 'Безопасность', fr: 'Sécurité', de: 'Sicherheit', tr: 'Güvenlik', pt: 'Segurança' },
  'trust.responsible': { ar: 'اللعب المسؤول', en: 'Responsible Gambling', es: 'Juego responsable', ru: 'Ответственная игра', fr: 'Jeu responsable', de: 'Verantwortungsvolles Spielen', tr: 'Sorumlu Oyun', pt: 'Jogo responsável' },

  // ---------- News hub & article pages (auto-published sports news) ----------
  'news.h1': { ar: 'أخبار الرياضة', en: 'Sports News', es: 'Noticias deportivas', ru: 'Спортивные новости', fr: 'Actualités sportives', de: 'Sport-Nachrichten', tr: 'Spor Haberleri', pt: 'Notícias esportivas' },
  'news.desc': { ar: 'أحدث أخبار عالم الرياضة من مصادر موثوقة — كرة القدم و十余 رياضة أخرى، تُحدَّث تلقائياً على مدار الساعة.', en: 'The latest sports news from trusted sources — football and 15+ other sports, updated automatically around the clock.', es: 'Las últimas noticias deportivas de fuentes fiables — fútbol y más de15 deportes, actualizadas automáticamente.', ru: 'Последние спортивные новости из надёжных источников — футбол и ещё 15+ видов спорта, обновляются автоматически.', fr: 'Les dernières actualités sportives de sources fiables — football et plus de15 autres sports, mises à jour automatiquement.', de: 'Die neuesten Sportnachrichten aus zuverlässigen Quellen — Fußball und 15+ weitere Sportarten, automatisch aktualisiert.', tr: 'Güvenilir kaynaklardan en güncel spor haberleri — futbol ve15+ başka spor dalı, otomatik güncellenir.', pt: 'As últimas notícias esportivas de fontes confiáveis — futebol e mais de15 outros esportes, atualizadas automaticamente.' },
  'news.updated': { ar: 'آخر تحديث: {date}', en: 'Updated: {date}', es: 'Actualizado: {date}', ru: 'Обновлено: {date}', fr: 'Mis à jour : {date}', de: 'Aktualisiert: {date}', tr: 'Güncelleme: {date}', pt: 'Atualizado: {date}' },
  'news.read_source': { ar: 'متابعة القراءة في {source}', en: 'Read the full story at {source}', es: 'Leer la noticia completa en {source}', ru: 'Читать полностью на {source}', fr: 'Lire l’article complet sur {source}', de: 'Vollständigen Artikel bei {source} lesen', tr: "{source} kaynağında okumaya devam et", pt: 'Ler a notícia completa em {source}' },
  'news.not_found': { ar: 'الخبر غير موجود أو لم يعد متاحاً.', en: 'News item not found or no longer available.', es: 'Noticia no encontrada o ya no disponible.', ru: 'Новость не найдена или больше недоступна.', fr: 'Actualité introuvable ou plus disponible.', de: 'Artikel nicht gefunden oder nicht mehr verfügbar.', tr: 'Haber bulunamadı veya artık mevcut değil.', pt: 'Notícia não encontrada ou indisponível.' },
  'news.related': { ar: 'أخبار ذات صلة', en: 'Related news', es: 'Noticias relacionadas', ru: 'Похожие новости', fr: 'Actualités associées', de: 'Ähnliche Nachrichten', tr: 'İlgili haberler', pt: 'Notícias relacionadas' },
  'news.empty': { ar: 'لا توجد أخبار منشورة بعد — عُد لاحقاً.', en: 'No news published yet — check back soon.', es: 'Aún no hay noticias — vuelve pronto.', ru: 'Новостей пока нет — загляните позже.', fr: 'Aucune actualité pour le moment — revenez bientôt.', de: 'Noch keine Nachrichten — schauen Sie bald vorbei.', tr: 'Henüz haber yok — yakında tekrar bakın.', pt: 'Nenhuma notícia ainda — volte em breve.' },
  'news.summary': { ar: 'الملخص', en: 'Summary', es: 'Resumen', ru: 'Краткое содержание', fr: 'Résumé', de: 'Zusammenfassung', tr: 'Özet', pt: 'Resumo' },
  'news.prev': { ar: 'السابق', en: 'Previous', es: 'Anterior', ru: 'Назад', fr: 'Précédent', de: 'Zurück', tr: 'Önceki', pt: 'Anterior' },
  'news.next': { ar: 'التالي', en: 'Next', es: 'Siguiente', ru: 'Вперёд', fr: 'Suivant', de: 'Weiter', tr: 'Sonraki', pt: 'Próximo' },
  'news.all': { ar: 'كل الأخبار', en: 'All news', es: 'Todas las noticias', ru: 'Все новости', fr: 'Toutes les actualités', de: 'Alle Nachrichten', tr: 'Tüm haberler', pt: 'Todas as notícias' },

  // ---------- 404 ----------
  'e404.msg': { ar: 'الصفحة غير موجودة — ربما تم نقلها أو حذفها.', en: 'Page not found — it may have moved or been removed.', es: 'Página no encontrada — puede haberse movido o eliminado.', ru: 'Страница не найдена — возможно, она была перемещена или удалена.', fr: 'Page introuvable — elle a peut-être été déplacée ou supprimée.', de: 'Seite nicht gefunden — sie wurde möglicherweise verschoben oder entfernt.', tr: 'Sayfa bulunamadı — taşınmış veya kaldırılmış olabilir.', pt: 'Página não encontrada — pode ter sido movida ou removida.' },
  'e404.popular': { ar: 'روابط شائعة', en: 'Popular links', es: 'Enlaces populares', ru: 'Популярные ссылки', fr: 'Liens populaires', de: 'Beliebte Links', tr: 'Popüler bağlantılar', pt: 'Links populares' },
};

export function t2(key: string, lang: Lang, vars?: Record<string, string>): string {
  const row = T2[key];
  let s = row ? (row[lang] || row['ar'] || '') : '';
  if (vars) for (const [k, v] of Object.entries(vars)) s = s.split(`{${k}}`).join(v);
  return s;
}

// combined lookup used by server routes
export function tt(key: string, lang: Lang, vars?: Record<string, string>): string {
  const row = T[key] || T2[key];
  let s = row ? (row[lang] || row['ar'] || '') : '';
  if (vars) for (const [k, v] of Object.entries(vars)) s = s.split(`{${k}}`).join(v);
  return s;
}
