import { Company } from '../src/types';

export const DEFAULT_COMPANIES: Company[] = [
  {
    id: 'CMP1XB001',
    name: '1XBET',
    name_ar: 'وان إكس بت (1XBET)',
    type: 'both',
    badge: 'بونص ترحيبي 130%',
    bonus_text: 'استرداد يصل لـ 100% + بونص 130%',
    details: 'أكبر منصات المراهنات الرياضية والألعاب مع بث حي ورهانات فورية وسحب سريع لكافة المحافظ',
    is_active: true,
    promo_code: 'vexwallet',
    affiliate_link: 'https://reffpa.com/L?tag=d_5955825m_45361c_&site=5955825&ad=45361',
    app_link: 'https://reffpa.com/L?tag=d_5955825m_2528c_&site=5955825&ad=2528',
    color: '#0d579b',
    description: 'أكبر شركات المراهنة عالمياً بعروض دورية وسرعة فائقة في السحب والإيداع',
    show_in_comp: true,
    api_config: {
      enabled: true,
      integration_type: 'rest_api',
      endpoint_url: 'https://api.1xbet.com/v1/agent/deposit',
      api_key: '1xb_live_sec_88492041284712',
      account_id_param: 'player_id',
      min_transfer_amount: 1,
      max_transfer_amount: 5000,
      allow_available_only: true,
      auto_payout: true,
      test_mode: false,
      last_test_status: 'success',
      last_test_at: new Date().toISOString(),
    },
  },
  {
    id: 'CMPMLB002',
    name: 'MELBET',
    name_ar: 'ميلبيت (MELBET)',
    type: 'both',
    badge: 'مضاعفة الإيداع الأول',
    bonus_text: 'فك تجميد يومي 10% + كاش باك أسبوعي',
    details: 'أفضل احتمالات الفوز وتغطية شاملة للدوريات العالمية مع سحب فوري وكاش باك أسبوعي سخي',
    is_active: true,
    promo_code: 'ml_3154096',
    affiliate_link: 'https://refpa39407.com/L?tag=d_5074314m_59685c_11&site=5074314&ad=59685&r=affilat',
    app_link: 'https://refpa3665.com/L?tag=d_5074314m_70867c_&site=5074314&ad=70867',
    color: '#f59e0b',
    description: 'منصة سريعة وموثوقة بنظام مكافآت ترحيبية استثنائي وتأمين كامل',
    show_in_comp: true,
    api_config: {
      enabled: true,
      integration_type: 'merchant_gateway',
      endpoint_url: 'https://merchant.melbet.org/api/v2/payout',
      merchant_id: 'ML_MERCHANT_9942',
      secret_key: 'ml_sec_hash_a99f821c900e',
      account_id_param: 'user_id',
      min_transfer_amount: 1,
      max_transfer_amount: 3000,
      allow_available_only: true,
      auto_payout: true,
      test_mode: false,
      last_test_status: 'success',
      last_test_at: new Date().toISOString(),
    },
  },
  {
    id: 'CMPBJ003',
    name: 'BETJAM',
    name_ar: 'بيت جام (BETJAM)',
    type: 'both',
    badge: 'النادي الملكي للكاش باك',
    bonus_text: 'تعويض فوري + تحويلات PIN آمنة',
    details: 'واجهة عصرية للمراهنات التنافسية وعروض استرداد نقدي سخية مع فك رصيد سلس',
    is_active: true,
    promo_code: 'VEDO2002',
    affiliate_link: 'https://refpa5124.com/L?tag=d_5089740m_96332c_&site=5089740&ad=96332',
    app_link: 'https://refpa5124.com/L?tag=d_5089740m_97988c_&site=5089740&ad=97988',
    color: '#8b5cf6',
    description: 'تطبيق سلس ومكافآت يومية للاعبين النشطين بنظام أمان مشفر',
    show_in_comp: true,
    api_config: {
      enabled: true,
      integration_type: 'webhook_s2s',
      endpoint_url: 'https://gateway.betjam.com/s2s/credit',
      api_key: 'bj_webhook_key_5510',
      webhook_url: 'https://vex.deals/api/callbacks/betjam',
      account_id_param: 'account_number',
      min_transfer_amount: 2,
      max_transfer_amount: 2000,
      allow_available_only: true,
      auto_payout: true,
      test_mode: false,
      last_test_status: 'success',
      last_test_at: new Date().toISOString(),
    },
  },
  {
    id: 'CMPMB004',
    name: 'MOSTBET',
    name_ar: 'موست بيت (MOSTBET)',
    type: 'both',
    badge: 'بونص ترحيبي 125%',
    bonus_text: '125% بونص إيداع + تأمين التذاكر المجمعة',
    details: 'مكافآت ترحيبية ضخمة تصل لـ 125% وسحب سريع لجميع المحافظ الإلكترونية. تأمين شامل على الرهانات الرياضية المجمعة واسترداد خسائر فوري.',
    is_active: true,
    promo_code: 'vedo2002',
    affiliate_link: 'https://mostbetegypt.com/0E2F',
    app_link: 'https://vgfiiimb.com/68fU',
    color: '#ef4444',
    description: 'علامة دولية شهيرة بالنزاهة والمدفوعات الفورية لكافة المحافظ والعملات الرقمية',
    show_in_comp: true,
    api_config: {
      enabled: true,
      integration_type: 'rest_api',
      endpoint_url: 'https://api.mostbet.com/v1/payout/agent',
      api_key: 'mb_prod_token_7721094',
      account_id_param: 'user_id',
      min_transfer_amount: 1,
      max_transfer_amount: 4000,
      allow_available_only: true,
      auto_payout: true,
      test_mode: false,
      last_test_status: 'success',
      last_test_at: new Date().toISOString(),
    },
  },
  {
    id: 'CMPXP005',
    name: 'XPARI',
    name_ar: 'إكسباري (XPARI / XPARIBET)',
    type: 'both',
    badge: 'أعلى كاش باك + تحليلات AI',
    bonus_text: 'أعلى استرداد كاش باك + تأمين الحساب',
    details: 'أعلى معدلات كاش باك وإحصائيات رياضية تحليلية مباشرة. تغطية واسعة للرياضات الإلكترونية والبطولات القارية وربط تلقائي بنظام التأمين.',
    is_active: true,
    promo_code: 'vedo2002',
    affiliate_link: 'https://xp-aff.com/L?tag=d_5912007m_64821c_site&site=5912007&ad=64821&r=registration',
    app_link: 'https://xp-aff.com/L?tag=d_5912007m_71587c_apk1&site=5912007&ad=71587',
    color: '#06b6d4',
    description: 'تغطية ذكية للرياضات والبطولات بأعلى نسبة استرداد نقدي كاش باك وتحديثات لحظية',
    show_in_comp: true,
    api_config: {
      enabled: true,
      integration_type: 'merchant_gateway',
      endpoint_url: 'https://merchant.xpari.com/api/deposit',
      merchant_id: 'XP_MERCHANT_3310',
      secret_key: 'xp_sec_key_7719234812',
      account_id_param: 'player_id',
      min_transfer_amount: 1,
      max_transfer_amount: 2500,
      allow_available_only: true,
      auto_payout: true,
      test_mode: false,
      last_test_status: 'success',
      last_test_at: new Date().toISOString(),
    },
  },
  {
    id: 'CMPBB006',
    name: 'BIZBET',
    name_ar: 'بيزبِت / باز (BIZBET)',
    type: 'both',
    badge: 'أمان مصرفي + سحوبات أسبوعية',
    bonus_text: 'تشفير بنكي كامل + دعم متواصل 24/7',
    details: 'تقنيات متطورة وأمان فائق في المعاملات مع دعم عربي على مدار الساعة. تشفير مصرفي عالي المستوى وسحوبات أسبوعية قيمة للمشتركين بكود الوكالة.',
    is_active: true,
    promo_code: 'bi_9258',
    affiliate_link: 'https://refpa83754.com/L?tag=d_5749248m_88828c_&site=5749248&ad=88828',
    app_link: 'https://refpa83754.com/L?tag=d_5749248m_67005c_&site=5749248&ad=67005',
    color: '#10b981',
    description: 'أحدث المنصات بتقنيات تشفير عالية وحوافز أسبوعية وسرعة معالجة استثنائية',
    show_in_comp: true,
    api_config: {
      enabled: true,
      integration_type: 'basic_auth',
      endpoint_url: 'https://partner.bizbet.com/api/v1/direct-credit',
      api_key: 'agent_bizbet_eg',
      secret_key: 'SecurePass_Bizbet#2026',
      account_id_param: 'account_id',
      min_transfer_amount: 1,
      max_transfer_amount: 2000,
      allow_available_only: true,
      auto_payout: true,
      test_mode: false,
      last_test_status: 'success',
      last_test_at: new Date().toISOString(),
    },
  },
  {
    id: 'CMPLB007',
    name: 'LINEBET',
    name_ar: 'لاين بيت (LINEBET)',
    type: 'both',
    badge: 'تطبيق خفيف وسريع',
    bonus_text: 'خيارات مراهنة غير محدودة + سرعة فائقة',
    details: 'منصة احترافية بخيارات مراهنة متنوعة وتطبيق خفيف وسريع متوافق مع كافة الأجهزة',
    is_active: true,
    promo_code: 'VEDO2002',
    affiliate_link: 'https://lb-aff.com/L?tag=d_5911847m_22611c_site&site=5911847&ad=22611&r=registration',
    app_link: 'https://lb-aff.com/L?tag=d_5911847m_66803c_apk1&site=5911847&ad=66803',
    color: '#22c55e',
    description: 'أداء مستقر وسرعة استجابة فائقة على مختلف الأجهزة وشبكة خوادم قوية',
    show_in_comp: true,
    api_config: {
      enabled: true,
      integration_type: 'oauth2_client',
      endpoint_url: 'https://api.linebet.com/oauth/v2/transfer',
      api_key: 'linebet_client_id_9921',
      secret_key: 'linebet_client_secret_xyz123',
      account_id_param: 'user_id',
      min_transfer_amount: 1,
      max_transfer_amount: 5000,
      allow_available_only: true,
      auto_payout: true,
      test_mode: false,
      last_test_status: 'success',
      last_test_at: new Date().toISOString(),
    },
  },
  {
    id: 'CMPGB008',
    name: 'GOOOBET',
    name_ar: 'جوووبت (GOOOBET)',
    type: 'both',
    badge: 'النادي الذهبي للمكافآت',
    bonus_text: 'تعويضات استثنائية + تسجيل فوري',
    details: 'عروض حصرية لتعويض الخسائر وسرعة تسجيل قياسية مع تغطية شاملة لجميع الأحداث الرياضية',
    is_active: true,
    promo_code: 'Vex',
    affiliate_link: 'https://gooobetaffiliate.com/L?tag=d_4531176m_95710c_&site=4531176&ad=95710',
    app_link: 'https://gooobetaffiliate.com/L?tag=d_4531176m_109867c_&site=4531176&ad=109867',
    color: '#eab308',
    description: 'باقة مميزة من المزايا ونظام تعويض استثنائي مع بونص ترحيبي مضاعف',
    show_in_comp: true,
    api_config: {
      enabled: true,
      integration_type: 'webhook_s2s',
      endpoint_url: 'https://s2s.gooobet.com/v1/player/deposit',
      api_key: 'gb_hook_token_8819',
      webhook_url: 'https://vex.deals/api/callbacks/gooobet',
      account_id_param: 'player_id',
      min_transfer_amount: 1,
      max_transfer_amount: 1500,
      allow_available_only: true,
      auto_payout: true,
      test_mode: false,
      last_test_status: 'success',
      last_test_at: new Date().toISOString(),
    },
  },
  {
    id: 'CMPWW009',
    name: 'WINWIN',
    name_ar: 'وين وين (WINWIN)',
    type: 'both',
    badge: 'كاش باك يومي 15%',
    bonus_text: 'تعويض تلقائي + بونص تراكمي',
    details: 'منصة رائدة بخدمات المراهنة التنافسية وباقات كاش باك يومية وسحوبات بنكية فائقة السرعة',
    is_active: true,
    promo_code: 'vexwallet',
    affiliate_link: 'https://winwin-aff.com/L?tag=d_6011244m_19284c_&site=6011244',
    app_link: 'https://winwin-aff.com/L?tag=d_6011244m_19284c_app&site=6011244',
    color: '#14b8a6',
    description: 'منصة حديثة تتميز باستقرار عالي ومكافآت يومية للاعبين النشطين',
    show_in_comp: true,
    api_config: {
      enabled: true,
      integration_type: 'rest_api',
      endpoint_url: 'https://api.winwin.com/v1/payout',
      api_key: 'winwin_key_884102',
      account_id_param: 'account_id',
      min_transfer_amount: 1,
      max_transfer_amount: 3000,
      allow_available_only: true,
      auto_payout: true,
      test_mode: false,
      last_test_status: 'success',
      last_test_at: new Date().toISOString(),
    },
  },
  {
    id: 'CMP888010',
    name: '888STARZ',
    name_ar: '888 ستارز (888STARZ)',
    type: 'both',
    badge: 'أعلى حوافز العملات الرقمية',
    bonus_text: 'استرداد فوري بالعملات المشفرة + أمان Web3',
    details: 'أول منصة هجينة تدعم التحويلات اللحظية بالعملات الرقمية والمحافظ التقليدية مع كاش باك لا ينتهي',
    is_active: true,
    promo_code: 'VEXDEALS',
    affiliate_link: 'https://888starz.bet/affiliate?tag=vexdeals',
    app_link: 'https://888starz.bet/download?tag=vexdeals',
    color: '#ea580c',
    description: 'تغطية مالية واسعة بأحدث تقنيات المدفوعات والتعويضات المشفرة',
    show_in_comp: true,
    api_config: {
      enabled: true,
      integration_type: 'merchant_gateway',
      endpoint_url: 'https://api.888starz.bet/agent/v2/transfer',
      merchant_id: 'STARZ_888_MERCHANT',
      secret_key: 'starz_sec_994821',
      account_id_param: 'user_id',
      min_transfer_amount: 1,
      max_transfer_amount: 5000,
      allow_available_only: true,
      auto_payout: true,
      test_mode: false,
      last_test_status: 'success',
      last_test_at: new Date().toISOString(),
    },
  },
  {
    id: 'CMPPP011',
    name: 'PARIPESA',
    name_ar: 'باري بيسا (PARIPESA)',
    type: 'both',
    badge: 'بونص ترحيبي 100%',
    bonus_text: 'سحب لحظي + تأمين الرهان الأول',
    details: 'أفضل احتمالات في كرة القدم والبطولات القارية مع حماية كاملة لحسابات الوكالة الرسمية',
    is_active: true,
    promo_code: 'vexwallet',
    affiliate_link: 'https://paripesa.com/affiliate?tag=vexwallet',
    app_link: 'https://paripesa.com/download?tag=vexwallet',
    color: '#3b82f6',
    description: 'منصة سريعة ومنتشرة عالمياً مع دعم محلي متواصل وسرعة فائقة',
    show_in_comp: true,
    api_config: {
      enabled: true,
      integration_type: 'basic_auth',
      endpoint_url: 'https://api.paripesa.com/v1/agent/credit',
      api_key: 'paripesa_agent_token',
      secret_key: 'pari_pass_2026',
      account_id_param: 'player_id',
      min_transfer_amount: 1,
      max_transfer_amount: 2500,
      allow_available_only: true,
      auto_payout: true,
      test_mode: false,
      last_test_status: 'success',
      last_test_at: new Date().toISOString(),
    },
  },
  {
    id: 'CMPBW012',
    name: 'BETWINNER',
    name_ar: 'بيت وينر (BETWINNER)',
    type: 'both',
    badge: 'بونص VIP وكاش باك شهري',
    bonus_text: 'تغطية خسائر حتى 20% + جوائز دورية',
    details: 'منصة كلاسيكية موثوقة تضم ملايين المستخدمين حول العالم مع خدمة VIP مخصصة لعملاء VEX Deals',
    is_active: true,
    promo_code: 'vexwallet',
    affiliate_link: 'https://betwinner.com/affiliate?tag=vexwallet',
    app_link: 'https://betwinner.com/download?tag=vexwallet',
    color: '#15803d',
    description: 'واحدة من أعرق وأشمل منصات المراهنات الرياضية عالمياً',
    show_in_comp: true,
    api_config: {
      enabled: true,
      integration_type: 'oauth2_client',
      endpoint_url: 'https://api.betwinner.com/v2/oauth/payout',
      api_key: 'bw_client_id_9901',
      secret_key: 'bw_secret_key_8841',
      account_id_param: 'user_id',
      min_transfer_amount: 1,
      max_transfer_amount: 4000,
      allow_available_only: true,
      auto_payout: true,
      test_mode: false,
      last_test_status: 'success',
      last_test_at: new Date().toISOString(),
    },
  },
];

export interface ServerCompensationRequest {
  id: string;
  user_id?: string;
  company_id: string;
  company_name: string;
  account_number: string;
  bet_slip_id: string;
  amount: number;
  status: 'pending' | 'approved' | 'rejected';
  created_at: string;
  reviewed_at?: string;
  reviewed_by?: string;
  rejection_reason?: string;
  note?: string;
  sender_ip?: string;
}

export const DEFAULT_COMPENSATION_REQUESTS: ServerCompensationRequest[] = [];

export interface ServerPhoneChangeRequest {
  id: string;
  user_id: string;
  current_phone: string;
  new_phone: string;
  reason: string;
  status: 'pending' | 'approved' | 'rejected';
  created_at: string;
  reviewed_at?: string;
  reviewed_by?: string;
  ip_address?: string;
}

export const DEFAULT_PHONE_CHANGE_REQUESTS: ServerPhoneChangeRequest[] = [];

export const DEFAULT_TELEGRAM_CONFIG = {
  bot_token: '7199284710:AAHq_DemoBotTokenForVexDealsPlatformTest',
  bot_username: 'VexDealsSecurityBot',
  is_active: true,
  channel_id: '@vexdeals_official',
  admin_chat_id: '123456789',
  auto_verify_phone: true,
  webhook_url: 'https://vex.deals/api/telegram/webhook',
  last_tested_at: new Date().toISOString(),
  last_test_status: 'success',
};

export const DEFAULT_APP_BRANDING = {
  appName: 'VEX Deals',
  tagline: 'منصة الولاء والتعويضات والتحليلات الرياضية الذكية',
  metaDescription: 'منصة VEX Deals الرسمية لتتبع محافظ شركات المراهنات، تعويضات الخسائر الرياضية، وإلغاء تجميد الإحالات',
  metaKeywords: 'VEX Deals, تعويضات, كاش باك, 1xbet, melbet, betjam, mostbet',
  contactEmail: 'support@vex.deals',
  supportPhone: '+9647700000000',
  iconType: 'preset' as const,
  presetIconId: 'emerald-shield',
  customIconUrl: '',
  uploadedIconData: '',
  iconResolution: { width: 512, height: 512 },
  themeColor: '#059669',
  backgroundColor: '#f8fafc',
  targetCompanyId: 'all',
  exclusiveMode: false,
  updatedAt: new Date().toISOString(),
  paymentMethods: [
    {
      id: 'pm_vodafone',
      nameAr: 'فودافون كاش',
      nameEn: 'Vodafone Cash',
      accountNumber: '01012345678',
      holderName: 'VEX Deals Official',
      descriptionAr: 'التحويل السريع والفوري عبر محفظة فودافون كاش المصرية',
      descriptionEn: 'Instant transfer via Vodafone Cash wallet',
      is_active: true,
    },
    {
      id: 'pm_instapay',
      nameAr: 'إنستا باي (InstaPay)',
      nameEn: 'InstaPay IPN',
      accountNumber: 'vexdeals@instapay',
      holderName: 'VEX Deals Egypt',
      descriptionAr: 'شبكة المدفوعات اللحظية - تحويل فوري مجاني من أي حساب بنكي',
      descriptionEn: 'Instant payment network - free transfer from any bank account',
      is_active: true,
    },
    {
      id: 'pm_etisalat',
      nameAr: 'اتصالات كاش',
      nameEn: 'Etisalat Cash',
      accountNumber: '01198765432',
      holderName: 'VEX Deals Official',
      descriptionAr: 'محفظة اتصالات كاش لاستلام وتحويل الأموال',
      descriptionEn: 'Etisalat Cash digital wallet',
      is_active: true,
    },
    {
      id: 'pm_orange',
      nameAr: 'أورانج كاش',
      nameEn: 'Orange Cash',
      accountNumber: '01233344455',
      holderName: 'VEX Deals Official',
      descriptionAr: 'محفظة أورانج كاش الرقمية المعتمدة',
      descriptionEn: 'Orange Cash digital wallet',
      is_active: true,
    },
    {
      id: 'pm_we',
      nameAr: 'وي باي (WE Pay)',
      nameEn: 'WE Pay',
      accountNumber: '01555667788',
      holderName: 'VEX Deals Official',
      descriptionAr: 'محفظة المصرية للاتصالات WE Pay',
      descriptionEn: 'WE Pay digital wallet',
      is_active: true,
    },
    {
      id: 'pm_bank',
      nameAr: 'تحويل بنكي محلي / ميزة',
      nameEn: 'Local Bank / Meeza',
      accountNumber: 'EG87000200012345678901',
      holderName: 'VEX Deals Financials',
      descriptionAr: 'تحويل مباشر لأي حساب بنكي مصري أو بطاقة ميزة الوطنية',
      descriptionEn: 'Direct transfer to any Egyptian bank account or Meeza card',
      is_active: true,
    },
  ],
  companyCustomWebsites: {
    'CMP1XB001': {
      promoCode: 'vexwallet',
      affiliateLink: 'https://reffpa.com/L?tag=d_5955825m_45361c_&site=5955825&ad=45361',
      appDownloadLink: 'https://reffpa.com/L?tag=d_5955825m_2528c_&site=5955825&ad=2528',
      sections: {
        overview: {
          titleAr: 'الوكالة الحصرية الرسمية لمنصة وان إكس بت (1XBET)',
          titleEn: 'Official Exclusive Agency for 1XBET',
          subtitleAr: 'أقوى العروض وبونص ترحيبي مضاعف',
          subtitleEn: 'Exclusive offers with doubled welcome bonus',
          contentAr: 'نوفر عبر كود الوكالة المعتمد vexwallet أعلى بونص ترحيبي يصل إلى 130% مع تأمين رصيد فوري وحماية شاملة من تقلبات الرهانات الرياضية.',
          contentEn: 'We provide through the approved agency code vexwallet up to 130% welcome bonus with instant wallet protection.',
          enabled: true,
        },
        cashbackPolicy: {
          titleAr: 'سياسة الاسترداد والتعويض الحصرية',
          titleEn: 'Exclusive Cashback & Compensation Policy',
          subtitleAr: 'استرداد نقدي فوري على الرهانات الخاسرة',
          subtitleEn: 'Instant loss recovery on eligible bets',
          contentAr: 'في حال واجهتك خسائر في قسائم الرهان الرياضية عبر حسابك الموثق بكود وكالتنا، يحق لك تقديم قسيمة الرهان عبر محفظة VEX Deals لاسترداد نسبة تصل إلى 100% كرصيد تعويض.',
          contentEn: 'Submit your bet slip in VEX Deals wallet to recover up to 100% compensation balance.',
          enabled: true,
        },
      },
    },
    'CMPMLB002': {
      promoCode: 'ml_3154096',
      affiliateLink: 'https://refpa39407.com/L?tag=d_5074314m_59685c_11&site=5074314&ad=59685&r=affilat',
      appDownloadLink: 'https://refpa3665.com/L?tag=d_5074314m_70867c_&site=5074314&ad=70867',
      sections: {
        overview: {
          titleAr: 'الشراكة الرسمية لميلبيت (MELBET)',
          titleEn: 'Official Agency for MELBET',
          subtitleAr: 'أفضل احتمالات ونظام كاش باك أسبوعي',
          subtitleEn: 'Best odds and weekly cashback',
          contentAr: 'انضم إلى منصة ميلبيت عبر كود الوكالة ml_3154096 للاستفادة من فك التجميد التلقائي والكاش باك الأسبوعي المتجدد.',
          contentEn: 'Join Melbet using agency code ml_3154096 to enjoy daily unfreezing and weekly cashback.',
          enabled: true,
        },
      },
    },
  },
};

export const DEFAULT_NOTIFICATIONS = [];

export const DEFAULT_AB_TEST_CAMPAIGNS: any[] = [
  {
    id: 'ab-camp-uefa-cl',
    name: 'اختبار نبرة الإشعار لمباريات دوري أبطال أوروبا (رسمي VIP مقابل حماسي مباشر)',
    theme: 'sports_tactical',
    contrastType: 'linguistic_style',
    agentId: 'agent_marketing_partners',
    agentName: 'وكيل التسويق والتوطين الثقافي',
    status: 'completed',
    createdAt: new Date(Date.now() - 3600000 * 5).toISOString(),
    variantA: {
      id: 'A',
      name: 'النسخة أ - فصحى راقية ورسمية (VIP Prestige)',
      title: '👑 تغطية حصرية VIP: استرداد نقدي 100% وبونص النخبة على قمة الليلة',
      message: 'نقدم لك أعلى درجات الحماية وتأمين الرصيد 1:1 عبر VEX Deals مع رمز الترويج المعتمد. استمتع بتجربة رهان آمنة بلا مخاطر.',
      ctaText: 'فعّل تأمين الـ VIP واسترد رصيدك',
      ctaAction: 'https://vexdeals.com/vip-cashback',
      linguisticStyle: 'فصحى راقية ورسمية (VIP Prestige)',
      toneDescriptionAr: 'لغة رصينة تركز على الأمان المالي والسمعة المرموقة لعملاء النخبة',
      toneDescriptionEn: 'Refined formal standard Arabic emphasizing elite financial security',
      sampleSent: 1250,
      clicks: 148,
      ctr: 11.84,
    },
    variantB: {
      id: 'B',
      name: 'النسخة ب - عامية حماسية ومباشرة (High-Energy Action)',
      title: '⚡ الماتش مولع الليلة! فك تجميدك فوراً واسترجع 100% كاش باك!',
      message: 'ماتسيبش فرصتك تضيع! سجل بالبروموكود الحصري وخد تعويض كامل عن أي خسارة من محفظة VEX في ثواني معدودة.',
      ctaText: 'استرجع كاش باك الـ 100% الآن!',
      ctaAction: 'https://vexdeals.com/instant-claim',
      linguisticStyle: 'عامية حماسية ومباشرة (High-Energy Action)',
      toneDescriptionAr: 'لغة عفوية سريعة ومثيرة للحماس تركز على سرعة الاسترداد وتجنب تفويت الفرصة (FOMO)',
      toneDescriptionEn: 'Conversational, energetic copy driving immediate urgency and FOMO',
      sampleSent: 1250,
      clicks: 215,
      ctr: 17.2,
    },
    regionalResonance: [
      {
        cohortId: 'cohort_ar_eg',
        regionNameAr: 'مصر وبلاد الشام',
        regionNameEn: 'Egypt & Levant',
        flag: '🇪🇬',
        scoreA: 64,
        scoreB: 92,
        preferredVariant: 'B',
        reasonAr: 'الجمهور المصري يفضل النبرة الحماسية السريعة ("الماتش مولع") والمكسب المباشر السريع، مما ضاعف نسبة النقر CTR.',
        reasonEn: 'Egyptian users resonate heavily with enthusiastic match slang and immediate unfreeze terminology.',
      },
      {
        cohortId: 'cohort_ar_gulf',
        regionNameAr: 'دول الخليج العربي (VIP)',
        regionNameEn: 'Gulf Cooperation Council (VIP)',
        flag: '🇸🇦',
        scoreA: 91,
        scoreB: 68,
        preferredVariant: 'A',
        reasonAr: 'مستخدمو الخليج يفضلون النبرة الفاخرة والضمانات المالية المرموقة (VIP Prestige) على العامية السريعة.',
        reasonEn: 'Gulf users strongly favor prestige, elite cashback perks, and formal reliability guarantees.',
      },
      {
        cohortId: 'cohort_fr_maghreb',
        regionNameAr: 'المغرب العربي والفرانكفونية',
        regionNameEn: 'North Africa & Francophone',
        flag: '🇲🇦',
        scoreA: 72,
        scoreB: 85,
        preferredVariant: 'B',
        reasonAr: 'الجمهور المغاربي ينجذب أكثر للدعوة المباشرة الواضحة للعمل (Action-Oriented CTA) مع ضمان استرداد 100%.',
        reasonEn: 'Maghreb users respond better to clear, high-velocity refund guarantees.',
      },
      {
        cohortId: 'cohort_en_global',
        regionNameAr: 'المستخدمون الدوليون (الإنجليزية)',
        regionNameEn: 'International / Global',
        flag: '🌍',
        scoreA: 80,
        scoreB: 82,
        preferredVariant: 'B',
        reasonAr: 'تقارب كبير في التفاعل مع تفوق طفيف للصيغة المباشرة والسريعة.',
        reasonEn: 'Even split with slight preference toward actionable tactical refund wording.',
      },
      {
        cohortId: 'cohort_ru_cis',
        regionNameAr: 'رابطة الدول المستقلة وشرق أوروبا',
        regionNameEn: 'CIS & Eastern Europe',
        flag: '🇷🇺',
        scoreA: 88,
        scoreB: 74,
        preferredVariant: 'A',
        reasonAr: 'المستخدمون في أوروبا الشرقية يفضلون الشروط الدقيقة والضمانات الرسمية الواضحة دون مبالغة.',
        reasonEn: 'CIS users favor explicit contractual refund guarantees and exact figures over hype.',
      },
    ],
    hypothesisAr: 'هل تؤدي النبرة الحماسية السريعة الموجهة لجمهور الملاعب إلى زيادة معدل النقر مقارنة بالنبرة الرسمية الموجهة لكبار العملاء في مختلف الدول؟',
    hypothesisEn: 'Does high-energy urgency outperform prestige VIP assurance across differing regional cultural demographics?',
    winner: 'B',
    winnerReasonAr: 'حققت النسخة ب معدل نقر إجمالي 17.2% مقابل 11.8% للنسخة أ (+45% تفاعل)، مع تفوق ساحق في مصر والشام والمغرب العربي، بينما تفوقت النسخة أ في دول الخليج.',
    category: 'ai_prediction',
    urgency: 'urgent',
  },
  {
    id: 'ab-camp-cta-cashback',
    name: 'اختبار زر الدعوة للإجراء (CTA): الأمان واسترداد الأموال مقابل البونص المضاعف 130%',
    theme: 'compensation',
    contrastType: 'call_to_action',
    agentId: 'agent_marketing_partners',
    agentName: 'وكيل التسويق والتوطين الثقافي',
    status: 'draft',
    createdAt: new Date(Date.now() - 3600000 * 2).toISOString(),
    variantA: {
      id: 'A',
      name: 'النسخة أ - تركيز على الأمان واسترداد 100% (Safety & Guarantee CTA)',
      title: '🛡️ تأمين كامل ضد خسارة الرهان: استرجع رصيدك 1:1 فوراً',
      message: 'مهما كانت نتيجة المباراة، محفظة VEX Deals تضمن لك استرداد 100% من خسارتك وفك تجميد الرصيد فور إدخال رقم القسيمة.',
      ctaText: 'أمّن رهانك الآن واسترد خسارتك 100%',
      ctaAction: 'https://vexdeals.com/guarantee',
      linguisticStyle: 'تركيز على الأمان المالي واسترداد القيمة',
      toneDescriptionAr: 'رسالة مطمئنة تزيل المخاطر وتبعث على الثقة الكاملة',
      toneDescriptionEn: 'Risk-reversal messaging focused on total balance protection and trust',
      sampleSent: 0,
      clicks: 0,
      ctr: 0,
    },
    variantB: {
      id: 'B',
      name: 'النسخة ب - تركيز على البونص الضخم 130% (Greed / Maximizer CTA)',
      title: '🎁 ضاعف رصيدك الآن: بونص 130% حصري عبر كود الترويج المعتمد',
      message: 'احصل فوراً على 130% بونص ترحيبي مضاعف على إيداعك الجديد واستفد من أرباحك الإضافية في جميع البطولات الكبرى.',
      ctaText: 'اضغط هنا لمضاعفة إيداعك 130% فوراً!',
      ctaAction: 'https://vexdeals.com/bonus130',
      linguisticStyle: 'تركيز على تعظيم المكاسب والبونص السخي',
      toneDescriptionAr: 'رسالة تحفيزية تركز على القيمة المادية المضافة ومضاعفة الأرباح',
      toneDescriptionEn: 'Value-maximization messaging focused on lucrative bonus magnification',
      sampleSent: 0,
      clicks: 0,
      ctr: 0,
    },
    regionalResonance: [
      {
        cohortId: 'cohort_ar_eg',
        regionNameAr: 'مصر وبلاد الشام',
        regionNameEn: 'Egypt & Levant',
        flag: '🇪🇬',
        scoreA: 86,
        scoreB: 79,
        preferredVariant: 'A',
        reasonAr: 'تأمين الخسائر وفك تجميد الرصيد (النسخة أ) يمثل الهاجس الأكبر للاعبين في مصر نظراً لتقلبات العملة ورغبتهم في حفظ رأس المال.',
        reasonEn: 'Loss insurance and capital preservation resonate stronger than bonus wagering requirements.',
      },
      {
        cohortId: 'cohort_ar_gulf',
        regionNameAr: 'دول الخليج العربي (VIP)',
        regionNameEn: 'Gulf Cooperation Council (VIP)',
        flag: '🇸🇦',
        scoreA: 89,
        scoreB: 74,
        preferredVariant: 'A',
        reasonAr: 'عملاء الخليج يبحثون عن الموثوقية والأمان أكثر من البحث عن بونص بمتطلبات تدوير معقدة.',
        reasonEn: 'Gulf high-rollers prioritize frictionless risk coverage and guaranteed payouts.',
      },
      {
        cohortId: 'cohort_fr_maghreb',
        regionNameAr: 'المغرب العربي والفرانكفونية',
        regionNameEn: 'North Africa & Francophone',
        flag: '🇲🇦',
        scoreA: 78,
        scoreB: 91,
        preferredVariant: 'B',
        reasonAr: 'الجمهور المغاربي يبدي اهتماماً كبيراً بنسب البونص الترحيبي العالية لمضاعفة رأس المال البدائي.',
        reasonEn: 'Maghreb demographic shows very high appetite for 130% deposit multiplier promotions.',
      },
      {
        cohortId: 'cohort_en_global',
        regionNameAr: 'المستخدمون الدوليون (الإنجليزية)',
        regionNameEn: 'International / Global',
        flag: '🌍',
        scoreA: 84,
        scoreB: 83,
        preferredVariant: 'A',
        reasonAr: 'توازن دقيق مع ميل طفيف للضمان الصريح ضد الخسارة.',
        reasonEn: 'Balanced reception with slight bias towards transparent money-back assurance.',
      },
      {
        cohortId: 'cohort_ru_cis',
        regionNameAr: 'رابطة الدول المستقلة وشرق أوروبا',
        regionNameEn: 'CIS & Eastern Europe',
        flag: '🇷🇺',
        scoreA: 82,
        scoreB: 87,
        preferredVariant: 'B',
        reasonAr: 'لاعبو رابطة الدول المستقلة متمرسون في عروض البونص ويبحثون دائماً عن أعلى نسبة ترويجية.',
        reasonEn: 'CIS users are experienced bonus-hunters who look for maximum initial leverage.',
      },
    ],
    hypothesisAr: 'هل يتفوق زر الدعوة المبني على استرداد الخسارة بنسبة 100% على زر البونص الترحيبي 130% في تحويل المشتركين المترددين؟',
    hypothesisEn: 'Does a 100% loss-protection CTA convert hesitant bettors more effectively than a 130% deposit bonus CTA?',
    winner: null,
    winnerReasonAr: 'قيد التجربة المبدئية. تشير التوقعات إلى تفوق النسخة أ في الشرق الأوسط وتفوق النسخة ب في المغرب العربي وأوروبا الشرقية.',
    category: 'compensation',
    urgency: 'non-urgent',
  },
];
